Repository ONSdigital/design-system, pull requests merged in 2019-02, with the labels that each got.

#108 Issue #104: Lists need left padding and bottom margin
  src/components/breadcrumb/index.njk
  src/components/input/index.njk
  src/components/pagination/index.njk
  src/components/panel/examples/information-spacious/index.njk
  src/patterns/error-validation/index.njk
  src/patterns/playback/index.njk
  src/styles/colours/index.njk
  src/styles/typography/index.njk
  src/styles/typography/lists/src/_list.scss
  src/styles/typography/lists/src/_template.njk
Labels: bug

#150 7 header
  package-lock.json
  src/components/button/_button.scss
  src/components/button/_template.njk
  src/components/footer/_template.njk
  src/components/header/_header-nav.scss
  src/components/header/_header.scss
  src/components/header/_macro-options.md
  src/components/header/_template.njk
  src/components/header/examples/business/index.njk
  src/components/header/examples/external-basic/index.njk
  src/components/header/examples/external-hero/index.njk
  src/components/header/examples/external-navigation/index.njk
  src/components/header/examples/external-welsh/index.njk
  src/components/header/examples/internal-basic/index.njk
  src/components/header/examples/internal-service/index.njk
  src/components/header/examples/social/index.njk
  src/components/header/header-nav.js
  src/components/header/index.njk
  src/components/language-selector/_template.njk
  src/components/navigation/_navigation.scss
  src/components/navigation/_template.njk
  src/img/icons/icons--chevron-down-white.svg
  src/img/icons/icons--chevron-right-white.svg
  src/img/ons-logo-white.svg
  src/js/index.js
  src/scss/base/_print.scss
  src/scss/objects/_container.scss
  src/tests/config/karma.conf.common.js
  src/tests/spec/header-navigation/header-navigation.spec.js
  src/tests/spec/tabs/tabs.spec.js
  src/views/layouts/_example.njk
  src/views/layouts/_home.njk
  src/views/layouts/_master.njk
  src/views/layouts/_page.njk
Labels: Component

#183 Polyfill fetch and AbortController
  package.json
  src/js/fetch.js
  src/js/polyfills/abortable-fetch.js
  src/js/polyfills/index.js
  yarn.lock
Labels: enhancement
