Repository ONSdigital/design-system, pull requests merged in 2021-09, with the labels that each got.

#1646 Refine process for adding proposals to backlog
  .github/ISSUE_TEMPLATE/feature_request.md
  src/pages/contribute/community-backlog/index.njk
  src/pages/contribute/propose-a-change/index.njk
Labels: Documentation

#1630 Add search to new build system
  gulpfile.js
  lib/rendering/helpers/site-map.js
  lib/rendering/search-index-pipe.js
  src/components/accordion/index.njk
  src/components/address-input/index.njk
  src/components/autosuggest/_autosuggest.scss
  src/components/autosuggest/_macro.njk
  src/components/autosuggest/autosuggest.ui.js
  src/components/autosuggest/code.list.searcher.js
  src/components/autosuggest/index.njk
  src/components/back-link/index.njk
  src/components/button/_button.scss
  src/components/button/_macro.njk
  src/components/call-to-action/index.njk
  src/components/card/index.njk
  src/components/checkboxes/index.njk
  src/components/collapsible/index.njk
  src/components/downloads/index.njk
  src/components/header/_header-nav.scss
  src/components/header/_header.scss
  src/components/header/_macro.njk
  src/components/header/header-nav.dom.js
  src/components/header/header-nav.js
  src/components/header/index.njk
  src/components/hero/index.njk
  src/components/icons/_macro.njk
  src/components/input/_input.scss
  src/components/input/index.njk
  src/components/label/_label.scss
  src/components/label/_macro.njk
  src/components/label/index.njk
  src/components/metadata/index.njk
  src/components/pagination/index.njk
  src/components/related-content/index.njk
  src/components/related-links/index.njk
  src/components/search/_search.scss
  src/components/select/index.njk
  src/components/share-page/index.njk
  src/components/summary/index.njk
  src/components/table/index.njk
  src/components/textarea/index.njk
  src/components/timeline/index.njk
  src/components/upload/index.njk
  src/components/video/index.njk
  src/pages/get-started/npm/index.njk
  src/scss/objects/_container.scss
  src/scss/objects/_page.scss
  src/scss/utilities/_visibility.scss
  src/search-index.json
  src/styles/colours/index.njk
  src/styles/grid/index.njk
  src/styles/images/index.njk
  src/styles/typography/index.njk
  src/tests/spec/header-navigation/header-navigation.spec.js
  src/views/layouts/_page.njk
Labels: Do not merge

#1627 Design System - Updated docs for using scripts via npm
  src/pages/guidance/css-js-assets/index.njk
  src/scss/patternlib.scss
Labels: Do not merge

#1682 Updated top level section descriptions and landing page content
  src/components/index.njk
  src/foundations/index.njk
  src/foundations/typography/index.njk
  src/pages/guidance/index.njk
  src/pages/index.njk
  src/patterns/index.njk
Labels: Documentation

#1681 Date/Duration component - Refactor label and legend properties
  src/components/date-input/_macro-options.md
  src/components/date-input/_macro.njk
  src/components/date-input/examples/date-input-error/index.njk
  src/components/date-input/examples/date-input/index.njk
  src/components/duration/_macro-options.md
  src/components/duration/_macro.njk
  src/components/duration/examples/duration-address-error/index.njk
  src/components/duration/examples/duration-address/index.njk
  src/components/duration/examples/duration-error/index.njk
  src/components/input/_macro.njk
  src/tests/spec/mutually-exclusive/mutually-exclusive-duration.spec.js
Labels: Breaking changes

#1689 Answer description content guidance for radios/checkboxes
  src/components/checkboxes/examples/checkboxes-descriptions/index.njk
  src/components/checkboxes/index.njk
  src/components/radios/index.njk
Labels: Documentation

#1692 Content guide for basic principles
  lib/rendering/helpers/sub-navigation-helper.js
  src/foundations/typography/index.njk
  src/pages/guidance/basic-content-principles/index.njk
  src/pages/guidance/page-titles-and-urls/index.njk
Labels: Documentation

#1693 Content guidance for question pattern
  src/pages/guidance/headings/index.njk
  src/patterns/question/examples/question-anatomy/index.njk
  src/patterns/question/index.njk
Labels: Documentation

#1694 Added punctuation content guidance
  src/components/address-input/index.njk
  src/components/button/index.njk
  src/foundations/typography/index.njk
  src/foundations/typography/lists/examples/list/index.njk
  src/pages/guidance/page-titles-and-urls/index.njk
  src/pages/guidance/punctuation-principles/index.njk
  src/patterns/error-status-pages/index.njk
Labels: Documentation

#1696 Removed duplicate content guide
  src/pages/guidance/headings/index.njk
Labels: Bug, Documentation

#1699 Fix python compatibility issue ===
  src/components/content-pagination/_macro.njk
  src/components/hero/_macro.njk
  src/components/input/_macro.njk
  src/components/lists/_macro.njk
  src/components/share-page/_macro.njk
  src/views/layouts/_page.njk
Labels: Bug

#1698 Removed whitespace between example tabs
  src/views/partials/example/_example.scss
  src/views/partials/example/_macro.njk
Labels: Bug

#1700 Fix isArray issue with python
  lib/rendering/create-nunjucks-environment.js
  src/components/button/_macro.njk
  src/components/lists/_macro.njk
Labels: Bug

#1706 Change button examples to use variant and remove disabled param
  src/components/button/_macro.njk
  src/components/button/examples/button-download/index.njk
  src/components/button/examples/button-print/index.njk
Labels: Bug, Breaking changes
