Repository ONSdigital/design-system, pull requests merged in 2021-11, with the labels that each got.

#1732 Checkboxes/radios - Add select all and allow under 'other' reveal
  src/components/button/_button.scss
  src/components/checkboxes/_checkbox-macro.njk
  src/components/checkboxes/_checkbox.scss
  src/components/checkboxes/_macro-options.md
  src/components/checkboxes/_macro.njk
  src/components/checkboxes/checkbox-with-autoselect.js
  src/components/checkboxes/checkbox-with-fieldset.js
  src/components/checkboxes/checkboxes-with-reveal.js
  src/components/checkboxes/checkboxes.dom.js
  src/components/checkboxes/examples/checkboxes-autoselect/index.njk
  src/components/checkboxes/examples/checkboxes-borderless/index.njk
  src/components/checkboxes/examples/checkboxes-other-checkboxes/index.njk
  src/components/checkboxes/examples/checkboxes-other-radios/index.njk
  src/components/checkboxes/index.njk
  src/components/fieldset/_fieldset.scss
  src/components/radios/_macro-options.md
  src/components/radios/_macro.njk
  src/components/radios/_radios.scss
  src/components/radios/examples/radios-borderless/index.njk
  src/components/radios/examples/radios-other-checkboxes/index.njk
  src/components/radios/examples/radios-other-radios/index.njk
  src/components/radios/examples/radios-other/index.njk
  src/components/radios/index.njk
  src/components/radios/radios.dom.js
  src/tests/spec/checkboxes/checkboxes-with-autoselect.spec.js
  src/tests/spec/checkboxes/checkboxes-with-reveal-and-fieldset.spec.js
  src/tests/spec/radios/radios.spec.js
Labels: Enhancement

#1743 Make summary headings mandatory
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/index.njk
Labels: Accessibility, Breaking changes

#1744 Remove use of classes in table variants
  src/components/table/_macro-options.md
  src/components/table/_macro.njk
  src/components/table/_table.scss
  src/components/table/examples/table-compact/index.njk
  src/components/table/examples/table-numeric/index.njk
  src/components/table/examples/table-responsive/index.njk
  src/components/table/examples/table-scrollable/index.njk
  src/components/table/examples/table-sortable/index.njk
  src/components/table/index.njk
  src/tests/spec/table/table-scrollable.spec.js
  src/tests/spec/table/table-sortable.spec.js
Labels: Breaking changes

#1746 Aligned styles of indented components
  src/components/checkboxes/_checkbox.scss
  src/components/collapsible/_collapsible.scss
  src/components/summary/examples/summary-grouped/index.njk
  src/components/text-indent/_text-indent.scss
  src/patterns/pages/hub-and-spoke/examples/hub/index.njk
  src/scss/vars/_colors.scss
Labels: Enhancement

#1751 Allow header titles to wrap above medium breakpoint
  src/components/header/_header.scss
  src/components/header/_macro.njk
  src/components/input/_macro.njk
  src/patterns/ask-users-for/email-addresses/index.njk
  src/patterns/help-users-to/correct-errors/examples/errors-proto/errors/index.njk
  src/patterns/help-users-to/correct-errors/examples/errors-proto/index.njk
Labels: Bug

#1759 Changed question and fieldset description tags from span to div
  src/components/fieldset/_macro.njk
  src/components/question/_macro.njk
  src/components/question/examples/question-fieldset/index.njk
Labels: Bug

#1760 Removed deprecated related links component
  src/components/related-links/_macro.njk
  src/components/related-links/_related-links.scss
  src/components/related-links/examples/related-links-census/index.njk
  src/components/related-links/examples/related-links/index.njk
  src/components/related-links/index.njk
Labels: Breaking changes

#1767 Fix jinja compatability issue with radio 'other' selector
  src/components/radios/_macro.njk
Labels: Bug
