Repository ONSdigital/design-system, pull requests merged in 2021-03, with the labels that each got.

#1409 Footer logos using inline paths
  src/components/footer/_footer.scss
  src/components/footer/_macro.njk
  src/components/icons/_macro.njk
  src/img/UKOpenGovernmentLicence-grey.svg
  src/img/crest.svg
  src/img/nisra-logo-black-en.svg
  src/img/ons-logo-black-cy.svg
  src/img/ons-logo-black-en.svg
Labels: enhancement

#1405 Updated android and apple touch icons
  src/favicons/census/cy/android-chrome-192x192.png
  src/favicons/census/cy/android-chrome-512x512.png
  src/favicons/census/cy/apple-touch-icon.png
  src/favicons/census/en/android-chrome-192x192.png
  src/favicons/census/en/android-chrome-512x512.png
  src/favicons/census/en/apple-touch-icon.png
Labels: census, enhancement

#1410 Replaced document download placeholder graphic
  src/img/large/placeholder-portrait.png
  src/img/small/placeholder-portrait.png
Labels: census, enhancement

#1378 Updated some icons to include a consistent style of roundness
  src/components/content-pagination/_macro.njk
  src/img/icons--chevron-down.svg
Labels: census

#1415 Updated some icons to include a consistent style of roundness (Census)
  src/components/content-pagination/_macro.njk
  src/img/icons--chevron-down.svg
Labels: census, census branch

#1419 Social metadata (Census)
  src/favicons/census/cy/twitter.png
  src/favicons/census/en/twitter.png
  src/favicons/twitter.png
  src/styles/page-template/_template.njk
Labels: census, census branch

#1418 Footer logos inline svgs (Census)
  src/components/footer/_footer.scss
  src/components/footer/_macro.njk
  src/components/icons/_macro.njk
  src/img/UKOpenGovernmentLicence-grey.svg
  src/img/crest.svg
  src/img/nisra-logo-black-en.svg
  src/img/ons-logo-black-cy.svg
  src/img/ons-logo-black-en.svg
Labels: census, census branch

#1417 Social icons simplified (Census)
  src/favicons/census/cy/android-chrome-192x192.png
  src/favicons/census/cy/android-chrome-512x512.png
  src/favicons/census/cy/apple-touch-icon.png
  src/favicons/census/en/android-chrome-192x192.png
  src/favicons/census/en/android-chrome-512x512.png
  src/favicons/census/en/apple-touch-icon.png
Labels: census, census branch

#1416 Replaced document download placeholder graphic to bilingual (Census)
  src/img/large/placeholder-portrait.png
  src/img/small/placeholder-portrait.png
Labels: census, census branch

#1425 Removed min-width from checkbox__item if being used inside filters
  src/components/download-resources/_download-resources.scss
Labels: census

#1408 Adjust loader button spinner to center for all sizes
  src/components/button/_button.scss
Labels: census

#1413 Adjust loader button spinner to center for all sizes (Census)
  src/components/button/_button.scss
Labels: census, census branch

#1435 Revert "Footer logos inline svgs (Census)"
  src/components/footer/_footer.scss
  src/components/footer/_macro.njk
  src/components/icons/_macro.njk
  src/img/UKOpenGovernmentLicence-grey.svg
  src/img/crest.svg
  src/img/nisra-logo-black-en.svg
  src/img/ons-logo-black-cy.svg
  src/img/ons-logo-black-en.svg
Labels: census, census branch

#1422 Cookies - load gtm script immediately after save/accept
  src/components/cookies-banner/cookies-banner.js
  src/js/cookies-functions.js
  src/js/cookies-settings.js
  src/patterns/cookies-settings/examples/cookie-settings-page/index.njk
  src/tests/spec/cookies/cookies-banner.spec.js
Labels: Do not merge, breaking change, census, census branch

#1438 Updated promotional banner to allow for small and large source census
  src/components/promo-banner/_macro.njk
  src/components/promo-banner/examples/promo-banner-with-image/index.njk
  src/img/census-landscape.svg
Labels: census, census branch

#1441 Added new panel for important announcement
  src/components/icons/_macro.njk
  src/components/panel/_macro-options.md
  src/components/panel/_macro.njk
  src/components/panel/_panel.scss
  src/components/panel/examples/announcement/index.njk
  src/components/panel/index.njk
Labels: census

#1442 Add dark panel warning census
  src/components/icons/_macro.njk
  src/components/panel/_macro-options.md
  src/components/panel/_macro.njk
  src/components/panel/_panel.scss
  src/components/panel/examples/announcement/index.njk
  src/components/panel/index.njk
Labels: census, census branch

#1439 Hero banner adjustments with Nisra example census
  src/components/hero/_hero.scss
  src/components/hero/_macro.njk
  src/components/hero/examples/cymraeg/index.njk
  src/components/hero/examples/default/index.njk
  src/components/hero/examples/england/index.njk
  src/components/hero/examples/nisra-happening/index.njk
  src/components/hero/examples/nisra/index.njk
  src/components/hero/index.njk
  src/components/icons/_macro.njk
  src/img/its-about-us--dark.svg
  src/img/its-about-us--light.svg
  src/img/large/mother-and-daughter-in-ireland.jpg
  src/img/ni-syn-cyfrif--dark.svg
  src/img/ni-syn-cyfrif--light.svg
  src/img/small/mother-and-daughter-in-ireland.jpg
Labels: census, census branch

#1434 Removed min-width from checkbox__item if being used inside filters
  src/components/download-resources/_download-resources.scss
Labels: census, census branch

#1431 Updated promotional banner to allow for small and large source
  src/components/promo-banner/_macro.njk
  src/components/promo-banner/examples/promo-banner-with-image/index.njk
  src/img/census-landscape.svg
Labels: census

#1421 Cookies - load gtm script immediately after save/accept
  src/components/cookies-banner/cookies-banner.js
  src/js/cookies-functions.js
  src/js/cookies-settings.js
  src/patterns/cookies-settings/examples/cookie-settings-page/index.njk
  src/tests/spec/cookies/cookies-banner.spec.js
Labels: breaking change

#1428 Updated link as button behaviour for accessibility
  src/components/button/_macro.njk
  src/components/button/button.dom.js
  src/components/button/button.js
  src/components/button/index.njk
  src/components/download-resources/_download-resources.scss
  src/patterns/download-resources/examples/download-resources/index.njk
  src/tests/spec/button/link-button.spec.js
Labels: accessibility, breaking change

#1376 Hero banner adjustments with Nisra example
  src/components/hero/_hero.scss
  src/components/hero/_macro.njk
  src/components/hero/examples/cymraeg/index.njk
  src/components/hero/examples/default/index.njk
  src/components/hero/examples/england/index.njk
  src/components/hero/examples/nisra-happening/index.njk
  src/components/hero/examples/nisra/index.njk
  src/components/hero/index.njk
  src/components/icons/_macro.njk
  src/img/its-about-us--dark.svg
  src/img/its-about-us--light.svg
  src/img/large/mother-and-daughter-in-ireland.jpg
  src/img/ni-syn-cyfrif--dark.svg
  src/img/ni-syn-cyfrif--light.svg
  src/img/small/mother-and-daughter-in-ireland.jpg
Labels: census

#1433 Button links accessibiliy census
  src/components/button/_macro.njk
  src/components/button/button.dom.js
  src/components/button/button.js
  src/components/download-resources/_download-resources.scss
  src/patterns/download-resources/examples/download-resources/index.njk
  src/tests/spec/button/link-button.spec.js
Labels: breaking change, census, census branch

#1452 Cookies - fix return link on cookies settings confirmation message - census
  src/js/cookies-settings.js
Labels: census, census branch
