Repository ONSdigital/design-system, pull requests merged in 2022-09, with the labels that each got.

#2438 Simplify button macro
  src/components/button/_button.scss
  src/components/button/_macro-options.md
  src/components/button/_macro.njk
  src/components/button/_macro.spec.js
  src/components/button/button.spec.js
  src/components/button/examples/button-disabled/index.njk
  src/components/button/examples/button-download/index.njk
  src/components/button/examples/button-loader/index.njk
  src/components/button/examples/button-print/index.njk
  src/components/button/examples/button-timer/index.njk
  src/components/button/index.njk
  src/components/checkboxes/index.njk
  src/components/document-list/index.njk
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/_macro.spec.js
  src/components/header/examples/header-external-with-sub-navigation/index.njk
  src/components/navigation/_macro.njk
  src/components/navigation/_macro.spec.js
  src/components/question/_macro-options.md
  src/components/question/_macro.njk
  src/components/question/_macro.spec.js
  src/components/question/examples/question-interviewer-note/index.njk
  src/components/radios/index.njk
Labels: Enhancement, Breaking changes, Tech improvements

#2446 Download resources - revert example file
  src/patterns/help-users-to/download-resources/examples/download-resources/index.njk
Labels: Bug

#2444 Search component: allow an accesible icon only version of the button
  src/components/input/_macro.njk
  src/components/input/_macro.spec.js
  src/components/search/_macro-options.md
  src/components/search/_macro.njk
  src/components/search/_macro.spec.js
  src/components/search/examples/search-with-placeholder/index.njk
  src/components/search/examples/search/index.njk
Labels: Enhancement, Accessibility

#2441 Modal - allow GA tracking on events
  src/components/modal/_macro-options.md
  src/components/modal/_macro.njk
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/timeout-modal/_macro-options.md
  src/components/timeout-modal/_macro.njk
  src/components/timeout-modal/examples/timeout-modal/index.njk
  src/components/timeout-modal/index.njk
  src/components/timeout-modal/timeout-modal.js
  src/components/timeout-modal/timeout-modal.spec.js
Labels: Enhancement

#2435 Fix DAC issue convert summaries to use definition lists
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/_summary.scss
  src/components/summary/examples/summary-grouped-total/index.njk
  src/components/summary/examples/summary-grouped-with-errors/index.njk
  src/components/summary/examples/summary-grouped/index.njk
  src/components/summary/examples/summary-household-no-rows/index.njk
  src/components/summary/examples/summary-household/index.njk
  src/components/summary/examples/summary-hub/index.njk
  src/components/summary/examples/summary-multiple/index.njk
  src/components/summary/examples/summary-no-action/index.njk
  src/components/summary/examples/summary/index.njk
  src/components/summary/index.njk
  src/patterns/pages/hub-and-spoke/examples/hub-complete/index.njk
  src/patterns/pages/hub-and-spoke/examples/hub/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-summary/index.njk
Labels: Accessibility

#2452 Expose site search in page template currently as a non-documented feature to support service manual development.
  src/components/navigation/_macro.njk
Labels: Enhancement

#2451 Remove `dsExample` parameter from components and introduce `isDesignSystemExample` global.
  lib/rendering/render-page.js
  src/components/access-code/examples/access-code-error/index.njk
  src/components/button/_macro-options.md
  src/components/button/_macro.njk
  src/components/button/_macro.spec.js
  src/components/checkboxes/examples/checkboxes-error/index.njk
  src/components/date-input/_macro.spec.js
  src/components/date-input/examples/date-input-error/index.njk
  src/components/duration/_macro.spec.js
  src/components/duration/examples/duration-error/index.njk
  src/components/error/_macro.njk
  src/components/error/index.njk
  src/components/mutually-exclusive/examples/mutually-exclusive-date-with-error/index.njk
  src/components/panel/_macro-options.md
  src/components/panel/_macro.njk
  src/components/panel/_macro.spec.js
  src/components/panel/examples/panel-with-error-details/index.njk
  src/components/panel/examples/panel-with-error-summary/index.njk
  src/components/panel/examples/panel-with-success-message/index.njk
  src/components/radios/examples/radios-with-error/index.njk
  src/components/relationships/examples/relationships-error/index.njk
  src/components/select/examples/select-with-error/index.njk
  src/components/textarea/examples/textarea-error/index.njk
  src/components/upload/examples/upload-error/index.njk
  src/foundations/style/icons/examples/icons-size/index.njk
  src/patterns/ask-users-for/addresses/examples/address-input-manual-error/index.njk
  src/patterns/ask-users-for/email-addresses/examples/input-email-with-error/index.njk
  src/patterns/ask-users-for/feedback/examples/feedback-form-errors/index.njk
  src/patterns/ask-users-for/feedback/examples/feedback-success/index.njk
  src/patterns/ask-users-for/numeric-values/examples/input-number-suffixed-with-error/index.njk
  src/patterns/ask-users-for/phone-numbers/examples/phone-number-error/index.njk
  src/patterns/help-users-to/correct-errors/examples/error-details/index.njk
  src/patterns/help-users-to/correct-errors/examples/error-summary/index.njk
  src/patterns/help-users-to/find-a-support-centre/examples/postcode-error/index.njk
  src/patterns/help-users-to/save-and-sign-out/examples/signed-out/index.njk
  src/patterns/help-users-to/send-a-web-form/examples/errors/index.njk
  src/patterns/help-users-to/send-a-web-form/examples/success/index.njk
  src/tests/helpers/rendering.js
Labels: Tech improvements

#2447 Remove 'svgo' optimisation and replace `cssnano` with 'compressed' output style of scss processor.
  gulpfile.js
  package.json
  postcss.config.js
  src/static/img/UKOpenGovernmentLicence-grey.svg
  src/static/img/UKOpenGovernmentLicence.svg
  src/static/img/card-placeholder.svg
  src/static/img/census-landscape.svg
  src/static/img/census-logo-stacked-pos-billingual.png
  src/static/img/census-logo-stacked-pos-cy.png
  src/static/img/census-logo-stacked-pos-en.png
  src/static/img/census-promo-banner.svg
  src/static/img/circle-lines.svg
  src/static/img/dummy-brand-logo.svg
  src/static/img/icons--check.svg
  src/static/img/icons--chevron-down.svg
  src/static/img/its-about-us--dark.svg
  src/static/img/its-about-us--light.svg
  src/static/img/logo.svg
  src/static/img/ni-syn-cyfrif--dark.svg
  src/static/img/ni-syn-cyfrif--light.svg
  src/static/img/nisra-logo-black-en.svg
  src/static/img/ogl.svg
  src/static/img/ons-logo-black-cy.svg
  src/static/img/ons-logo-black-en.svg
  src/static/img/people-mob.png
  src/static/img/people.png
  src/static/img/rehearsal-areas.svg
  svgo-config.js
  yarn.lock
Labels: Tech improvements

#2427 Add tests and document that `currentPath` of navigation can be an array of strings.
  src/components/header/_macro-options.md
  src/components/header/examples/header-external-with-sub-navigation/index.njk
  src/components/navigation/_macro.njk
  src/components/navigation/_macro.spec.js
  src/components/section-navigation/_macro.njk
  src/views/layouts/_page.njk
Labels: Bug, Breaking changes
