Repository ONSdigital/design-system, pull requests merged in 2022-04, with the labels that each got.

#2043 Header - improve service (masthead) links on mobile
  src/components/button/_button.scss
  src/components/header/_header-nav.scss
  src/components/header/_header.scss
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/examples/census-nisra/index.njk
  src/components/header/examples/census/index.njk
  src/components/header/examples/external-description/index.njk
  src/components/header/examples/external-hero/index.njk
  src/components/header/examples/external-navigation/index.njk
  src/components/header/examples/external-service-links/index.njk
  src/components/header/examples/internal-basic/index.njk
  src/components/header/header-nav.dom.js
  src/components/header/header-nav.js
  src/components/header/index.njk
  src/foundations/layout/page-template/examples/block-areas/index.njk
  src/tests/spec/header-navigation/header-navigation.spec.js
Labels: Enhancement

#2103 Fix panel bug with no icon
  src/components/panel/_panel.scss
Labels: Bug

#2096 Add ability to set attributes on list items
  src/components/lists/_macro-options.md
  src/components/lists/_macro.njk
  src/foundations/style/typography/lists/examples/list-icon-social/index.njk
Labels: Breaking changes

#2045 Timeout modal - fix ie11 polyfill css
  src/components/modal/_macro.njk
  src/components/modal/_modal.scss
  src/components/modal/modal.js
  src/js/timeout.js
  src/tests/spec/timeout-modal/timeout-modal.spec.js
Labels: Bug
