Repository ONSdigital/design-system, pull requests merged in 2022-12, with the labels that each got.

#2541 Video only load when cookies enabled
  package.json
  src/components/table/_macro.spec.js
  src/components/video/_macro-options.md
  src/components/video/_macro.njk
  src/components/video/_macro.spec.js
  src/components/video/_video.scss
  src/components/video/examples/video/index.njk
  src/components/video/index.njk
  src/components/video/video.dom.js
  src/components/video/video.js
  src/components/video/video.spec.js
  src/js/main.js
  src/static/patternlib-img/youtube-example-cover.png
Labels: Bug

#2550 Remove redundant params from save and sign out button examples
  src/patterns/help-users-to/extend-session/examples/timeout/index.njk
  src/patterns/help-users-to/save-and-sign-out/examples/save-and-sign-out-button/index.njk
  src/patterns/pages/hub-and-spoke/examples/hub-complete/index.njk
  src/patterns/pages/hub-and-spoke/examples/hub/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-continue/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-start/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-summary/index.njk
Labels: Bug

#2547 Add flex style to summary action link
  src/components/summary/_summary.scss
Labels: Bug

#2537 Fix summary style for grouped household style answers
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/_summary.scss
  src/components/summary/examples/summary-grouped/index.njk
Labels: Bug

#2548 Change onsCollapsible to onsDetails, rename css classes
  src/components/access-code/examples/access-code-error/index.njk
  src/components/access-code/examples/access-code/index.njk
  src/components/accordion/_macro-options.md
  src/components/accordion/_macro.njk
  src/components/accordion/_macro.spec.js
  src/components/accordion/accordion.dom.js
  src/components/accordion/accordion.js
  src/components/accordion/accordion.spec.js
  src/components/accordion/index.njk
  src/components/button/_macro-options.md
  src/components/collapsible/_macro-options.md
  src/components/collapsible/_macro.njk
  src/components/collapsible/collapsible.dom.js
  src/components/collapsible/collapsible.js
  src/components/collapsible/collapsible.spec.js
  src/components/collapsible/index.njk
  src/components/details/_details.scss
  src/components/details/_macro-options.md
  src/components/details/_macro.njk
  src/components/details/_macro.spec.js
  src/components/details/details.dom.js
  src/components/details/details.js
  src/components/details/details.spec.js
  src/components/details/examples/details-with-saved-state/index.njk
  src/components/details/examples/details-with-warning/index.njk
  src/components/details/examples/details/index.njk
  src/components/details/index.njk
  src/components/hero/_hero.scss
  src/components/language-selector/_macro-options.md
  src/components/question/_macro-options.md
  src/components/question/_macro.njk
  src/components/question/_macro.spec.js
  src/components/question/examples/question-ccs/index.njk
  src/components/question/examples/question-fieldset/index.njk
  src/components/question/examples/question-interviewer-note/index.njk
  src/components/question/examples/question-no-fieldset/index.njk
  src/components/tabs/index.njk
  src/js/main.js
  src/pages/guidance/installing-the-design-system/using-css-js-and-assets/index.njk
  src/patterns/help-users-to/cookies-settings/examples/cookie-settings-page/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-start/index.njk
  src/patterns/pages/question/examples/question-anatomy/index.njk
  src/patterns/pages/question/index.njk
  src/scss/main.scss
  src/scss/objects/_page.scss
  src/scss/objects/_spacing.scss
  src/scss/overrides/hcm.scss
  src/scss/print.scss
  src/tests/visual/percy.snapshots.js
Labels: Mark-up change, Tech improvements

#2505 Update GA attributes on modals
  src/components/access-code/_macro.njk
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/timeout-modal/_macro.njk
  src/components/timeout-modal/timeout-modal.spec.js
  src/js/analytics.js
  src/js/timeout.js
  src/patterns/help-users-to/correct-errors/examples/errors-proto/errors/index.njk
  src/patterns/help-users-to/correct-errors/examples/errors-proto/index.njk
Labels: Enhancement

#2556 Added row of links to transactional example
  src/components/footer/examples/footer-transactional/index.njk
Labels: Bug, Documentation

#2554 Alignment issue on summaries
  src/components/summary/_macro.njk
  src/components/summary/_summary.scss
Labels: Bug
