Repository ONSdigital/design-system, pull requests merged in 2022-10, with the labels that each got.

#2464 Add macro option noInitialActiveTab for the tabs component
  src/components/tabs/_macro-options.md
  src/components/tabs/_macro.njk
  src/components/tabs/_macro.spec.js
  src/components/tabs/_tabs.scss
  src/components/tabs/examples/tabs-details/index.njk
  src/components/tabs/examples/tabs/index.njk
  src/components/tabs/index.njk
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: Enhancement

#2470 Fix: Design System section navigation unique IDs
  src/components/section-navigation/_macro-options.md
  src/components/section-navigation/_macro.njk
  src/views/layouts/_page.njk
Labels: Bug, Accessibility

#2471 Fix: CSS variables - invalid uses of css variables
  src/components/autosuggest/_autosuggest.scss
  src/components/download-resources/_download-resources.scss
  src/components/tabs/_tabs.scss
  src/pages/guidance/installing-the-design-system/using-css-js-and-assets/index.njk
  src/scss/settings/_census.scss
Labels: Bug

#2473 Add initial GA attributes to modal
  src/components/modal/modal.js
  src/components/modal/modal.spec.js
  src/components/timeout-modal/timeout-modal.spec.js
Labels: Bug

#2476 Look for `page.title` in `_template.njk` as a fallback.
  src/layout/_template.njk
Labels: Tech improvements

#2481 Adjust heading levels in "Email addresses" pattern.
  src/patterns/ask-users-for/email-addresses/index.njk
Labels: Tech improvements

#2488 Added new colour var for default hero bg
  src/components/hero/_hero.scss
  src/scss/vars/_colors.scss
Labels: Enhancement

#2490 Add `designSystemVersion` as fallback in layout template file.
  src/layout/_template.njk
Labels: Tech improvements

#2507 Consistently use font variables and added stylistic set 1 for Open Sans
  src/components/access-code/uac.scss
  src/components/autosuggest/_autosuggest.scss
  src/components/button/_button.scss
  src/components/download-resources/_download-resources.scss
  src/components/fieldset/_fieldset.scss
  src/components/navigation/_navigation.scss
  src/components/panel/_panel.scss
  src/components/summary/_summary.scss
  src/components/table/_table.scss
  src/foundations/style/colours/_colours.scss
  src/foundations/style/typography/index.njk
  src/patterns/pages/question/examples/question-anatomy/_pl-question-anatomy.scss
  src/scss/base/_typography.scss
  src/scss/patternlib.scss
  src/scss/utilities/_typography.scss
  src/scss/vars/_typography.scss
  src/static/fonts/opensans-bold.woff
  src/static/fonts/opensans-bold.woff2
  src/static/fonts/opensans-regular.woff
  src/static/fonts/opensans-regular.woff2
Labels: Enhancement, Do not merge

#2514 Remove find a support centre pattern and pages
  src/components/find-a-support-centre/_find-a-support-centre.scss
  src/pages/guidance/installing-the-design-system/using-css-js-and-assets/index.njk
  src/patterns/help-users-to/find-a-support-centre/examples/find/index.njk
  src/patterns/help-users-to/find-a-support-centre/examples/postcode-error/index.njk
  src/patterns/help-users-to/find-a-support-centre/examples/results/index.njk
  src/patterns/help-users-to/find-a-support-centre/index.njk
  src/scss/main.scss
  src/scss/settings/_census.scss
  src/scss/vars/_colors.scss
Labels: Streamlining
