Repository ONSdigital/design-system, pull requests merged in 2022-06, with the labels that each got.

#2231 Census - Upgrade core js to 2.6.12
  package.json
  yarn.lock
Labels: Census branch

#2260 Fix card macro and tests
  src/components/card/_macro-options.md
  src/components/card/_macro.njk
  src/components/card/_macro.spec.js
  src/components/card/examples/card-image/index.njk
Labels: Bug, Breaking changes

#2269 Fix/section nav
  src/components/section-navigation/_macro.njk
  src/components/section-navigation/_macro.spec.js
Labels: Bug

#2271 Fix/simple accordion tabindex
  src/components/collapsible/collapsible.js
  src/components/collapsible/collapsible.spec.js
Labels: Bug

#2270 List - fix BEM class on list element
  src/components/lists/_list.scss
  src/components/lists/_macro.njk
Labels: Bug

#2278 Fix: Failing Axe accessibility tests
  src/components/address-input/_macro-options.md
  src/components/address-input/_macro.spec.js
  src/components/autosuggest/_macro.njk
  src/components/autosuggest/_macro.spec.js
  src/components/duration/_macro.njk
  src/components/duration/_macro.spec.js
  src/components/duration/examples/duration-address-error/index.njk
  src/components/duration/examples/duration-address/index.njk
  src/components/duration/examples/duration-error/index.njk
  src/components/input/_input-type.scss
  src/components/input/_macro-options.md
  src/components/input/_macro.njk
  src/components/navigation/_macro.njk
  src/components/navigation/navigation.dom.js
  src/components/tabs/_macro.njk
Labels: Accessibility, Testing

#2284 Search placholder - fix alignment
  src/components/label/_label.scss
  src/components/search/_search.scss
  src/components/search/examples/search-character-check/index.njk
  src/components/search/examples/search/index.njk
Labels: Bug

#2288 Address input - fix error when manual input is `null`
  src/components/address-input/autosuggest.address.setter.js
Labels: Bug

#2290 Fix mutually exclusive bug for runner
  src/components/mutually-exclusive/_macro.njk
  src/components/mutually-exclusive/_macro.spec.js
  src/components/mutually-exclusive/examples/multiple-options/index.njk
Labels: Bug

#2293 Fix: Header - search button position on mobile in Safari
  src/components/header/_macro.njk
Labels: Bug

#2297 Fix poweredby Jinja2 error
  src/components/footer/_macro.njk
Labels: Bug
