Repository ONSdigital/design-system, pull requests merged in 2022-11, with the labels that each got.

#2491 Allow custom header logos and remove brand logos
  src/components/header/_header.scss
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/_macro.spec.js
  src/components/header/examples/header-branded-census2021/index.njk
  src/components/header/examples/header-default/index.njk
  src/components/header/examples/header-external-custom-organisation/index.njk
  src/components/header/examples/header-external-for-survey-with-description/index.njk
  src/components/header/examples/header-external-for-surveys/index.njk
  src/components/header/examples/header-external-welsh/index.njk
  src/components/header/examples/header-external-with-navigation/index.njk
  src/components/header/examples/header-external-with-service-links/index.njk
  src/components/header/examples/header-external-with-sub-navigation/index.njk
  src/components/header/examples/header-internal/index.njk
  src/components/header/examples/header-neutral-for-multicoloured-logo/index.njk
  src/components/header/examples/header-neutral-with-no-masthead/index.njk
  src/components/header/index.njk
  src/components/icons/_macro.njk
  src/components/icons/_macro.spec.js
  src/components/navigation/_macro.njk
  src/components/navigation/_macro.spec.js
  src/components/navigation/_navigation.scss
  src/components/status/index.njk
  src/foundations/layout/page-template/examples/base-page-template-block-areas/index.njk
  src/foundations/layout/page-template/examples/custom/index.njk
  src/foundations/layout/page-template/examples/themed/index.njk
  src/foundations/layout/page-template/index.njk
  src/layout/_template.njk
  src/patterns/ask-users-for/feedback/examples/feedback-form-errors/index.njk
  src/patterns/ask-users-for/feedback/examples/feedback-form/index.njk
  src/patterns/ask-users-for/feedback/examples/feedback-success/index.njk
  src/patterns/help-users-to/access-support-in-multiple-languages/examples/default/index.njk
  src/patterns/help-users-to/change-language/examples/cymraeg/index.njk
  src/patterns/help-users-to/change-language/examples/english-ireland/index.njk
  src/patterns/help-users-to/download-resources/examples/download-resources/index.njk
  src/patterns/help-users-to/extend-session/examples/timeout/index.njk
  src/patterns/help-users-to/save-and-sign-out/examples/save-and-sign-out-button/index.njk
  src/patterns/pages/guide/examples/guide-overview/index.njk
  src/patterns/pages/guide/examples/guide/index.njk
  src/patterns/pages/guide/examples/rtl/index.njk
  src/patterns/pages/hub-and-spoke/examples/hub-complete/index.njk
  src/patterns/pages/hub-and-spoke/examples/hub/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-continue/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-start/index.njk
  src/patterns/pages/hub-and-spoke/examples/spoke-summary/index.njk
  src/scss/vars/_colors.scss
  src/views/layouts/_page.njk
Labels: Enhancement, Do not merge, Breaking changes, Tech improvements, Streamlining

#2498 Remove theme config from base page template
  src/components/call-to-action/examples/call-to-action-census/index.njk
  src/components/hero/examples/hero-branded-census2021-engagement-with-strapline/index.njk
  src/components/hero/examples/hero-branded-census2021-engagement/index.njk
  src/components/hero/examples/hero-branded-census2021-with-call-to-action/index.njk
  src/components/hero/examples/hero-branded-ids/index.njk
  src/components/panel/examples/panel-with-announcement/index.njk
  src/components/panel/examples/panel-with-warning-for-branding/index.njk
  src/components/promotional-banner/examples/promotional-banner-with-image/index.njk
  src/components/promotional-banner/examples/promotional-banner/index.njk
  src/foundations/layout/page-template/examples/base-page-template-block-areas/index.njk
  src/foundations/layout/page-template/examples/themed/index.njk
  src/foundations/layout/page-template/index.njk
  src/layout/_template.njk
  src/patterns/help-users-to/access-support-in-multiple-languages/examples/default/index.njk
  src/views/layouts/_master.njk
Labels: Do not merge, Breaking changes, Tech improvements, Streamlining

#2500 Remove promo banner from DS
  config/components.json
  src/components/promotional-banner/_macro-options.md
  src/components/promotional-banner/_macro.njk
  src/components/promotional-banner/_macro.spec.js
  src/components/promotional-banner/_promo-banner.scss
  src/components/promotional-banner/examples/promotional-banner-with-image/index.njk
  src/components/promotional-banner/examples/promotional-banner/index.njk
  src/components/promotional-banner/index.njk
  src/scss/main.scss
  src/static/img/census-landscape.svg
Labels: Do not merge, Breaking changes, Tech improvements, Streamlining

#2501 Remove - Access support in multiple languages pattern
  src/components/select/select.js
  src/components/select/select.spec.js
  src/js/main.js
  src/patterns/help-users-to/access-support-in-multiple-languages/examples/default/index.njk
  src/patterns/help-users-to/access-support-in-multiple-languages/index.njk
Labels: Do not merge, Breaking changes, Tech improvements, Streamlining

#2503 Simplify hero component
  src/components/hero/_hero.scss
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/components/hero/examples/hero-branded-census2021-engagement-with-strapline/index.njk
  src/components/hero/examples/hero-branded-census2021-engagement/index.njk
  src/components/hero/examples/hero-branded-census2021-with-call-to-action/index.njk
  src/components/hero/examples/hero-branded-ids/index.njk
  src/components/hero/examples/hero-dark/index.njk
  src/components/hero/index.njk
  src/scss/vars/_colors.scss
Labels: Do not merge, Breaking changes, Streamlining

#2509 Add theme page
  src/pages/guidance/installing-the-design-system/compiled-html/index.njk
  src/pages/guidance/installing-the-design-system/custom-theme/index.njk
  src/pages/guidance/installing-the-design-system/using-css-js-and-assets/index.njk
Labels: Documentation, Streamlining

#2517 Hero - adjust how additional content is configured
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
Labels: Bug

#2519 Fix: Footer - crest logo position
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
  src/components/footer/examples/footer-with-alternative-organisation/index.njk
Labels: Bug

#2520 Use 'cors' package with 'dev-server.js'
  lib/dev-server.js
  package.json
  yarn.lock
Labels: Tech improvements

#2479 Fix: Downloadable resources - fix accessibility issues from DAC retest
  src/components/download-resources/download-resources.js
  src/components/download-resources/download-resources.spec.js
  src/patterns/help-users-to/download-resources/examples/download-resources/index.njk
Labels: Bug, Accessibility

#2522 Fix: Address autosuggest aria status message
  src/components/autosuggest/autosuggest.ui.js
Labels: Bug

#2527 Fix: Button - hover and active states for loader and disabled variants
  src/components/button/_button.scss
Labels: Bug

#2523 Fix: nested input error state
  src/components/checkboxes/_macro.njk
  src/components/radios/_macro.njk
Labels: Bug

#2528 Fix - pagination component: fix spacing issues
  src/components/pagination/_pagination.scss
Labels: Bug

#2530 Fix: Tabs component - check for hash in url update
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: Bug

#2532 Print - Update styles for navigation and remove search from print stylesheet
  src/scss/print.scss
Labels: Tech improvements

#2534 Change current page link background colour
  src/components/pagination/_pagination.scss
Labels: Bug

#2533 Add inline style from patternlib and remove unnecessary tabs from unique examples
  src/foundations/layout/grid/examples/grid-12/index.njk
  src/foundations/layout/grid/examples/grid-7-4/index.njk
  src/foundations/layout/grid/examples/grid-8/index.njk
  src/foundations/layout/grid/examples/grid-combo/index.njk
  src/foundations/layout/grid/index.njk
  src/foundations/layout/page-template/examples/base-page-template-block-areas/_block-areas.scss
  src/foundations/layout/page-template/examples/base-page-template-block-areas/index.njk
  src/foundations/style/colours/_colours.scss
  src/foundations/style/typography/headings/examples/breakpoint-headings/index.njk
  src/foundations/style/typography/headings/examples/default-heading-sizes/index.njk
  src/foundations/style/typography/highlighting/examples/highlighting/index.njk
  src/foundations/style/typography/index.njk
  src/foundations/style/typography/links/examples/link/index.njk
  src/foundations/style/typography/paragraphs/examples/paragraphs/index.njk
  src/patterns/pages/question/examples/question-anatomy/_pl-question-anatomy.scss
  src/patterns/pages/question/examples/question-anatomy/index.njk
  src/patterns/pages/question/index.njk
  src/scss/error.scss
  src/scss/patternlib.scss
  src/views/partials/example/_example.scss
Labels: Documentation, Tech improvements

#2546 Replaced type scale table with example
  src/foundations/style/typography/index.njk
  src/foundations/style/typography/type-scale/examples/type-scale/index.njk
Labels: Documentation

#2544 Fix page config welsh footer logo
  src/layout/_template.njk
Labels: Bug
