Repository ONSdigital/design-system, pull requests merged in 2022-02, with the labels that each got.

#1889 Added iconType and iconPosition to footer button
  src/components/footer/_macro.njk
Labels: Bug

#1891 Change CTA button icon to forward arrow
  src/components/button/_macro.njk
  src/foundations/style/icons/index.njk
Labels: Enhancement

#1893 Removed unnecessary button params
  src/components/button/_button.scss
  src/components/button/examples/button-custom/index.njk
  src/components/button/examples/button-disabled/index.njk
  src/components/button/examples/button-ghost/index.njk
  src/components/button/examples/button-group/index.njk
  src/components/button/examples/button-link-new-window/index.njk
  src/components/button/examples/button-link/index.njk
  src/components/checkboxes/_macro-options.md
  src/components/collapsible/index.njk
  src/components/header-navigation/_macro.njk
  src/components/header/_macro.njk
  src/components/header/examples/census-nisra/index.njk
  src/components/header/examples/census/index.njk
  src/components/header/examples/external-lang/index.njk
  src/components/header/examples/external-navigation/index.njk
  src/components/header/examples/external-ni-finance-dept/index.njk
  src/components/header/index.njk
  src/components/message-list/_macro-options.md
  src/components/pagination/_macro.njk
  src/components/summary/examples/hub/index.njk
  src/components/table-of-contents/index.njk
  src/components/tabs/index.njk
  src/foundations/layout/page-template/examples/block-areas/index.njk
  src/foundations/style/colours/index.njk
  src/pages/contribute/how-to-contribute/develop-a-feature/index.njk
  src/patterns/ask-users-for/relationships/index.njk
  src/patterns/help-users-to/cookies-settings/index.njk
  src/views/layouts/_page.njk
  src/views/partials/example/_macro.njk
Labels: Documentation

#1894 Moved highlighting documentation to foundations > typography
  src/foundations/layout/grid/index.njk
  src/foundations/layout/page-template/index.njk
  src/foundations/style/colours/index.njk
  src/foundations/style/icons/index.njk
  src/foundations/style/typography/highlighting/_highlight.scss
  src/foundations/style/typography/highlighting/examples/highlighting/index.njk
  src/foundations/style/typography/index.njk
  src/foundations/style/typography/paragraphs/examples/index.njk
  src/patterns/help-users-to/see-important-information/examples/see-important-information/index.njk
  src/patterns/help-users-to/see-important-information/index.njk
  src/patterns/pages/question/index.njk
  src/scss/main.scss
Labels: Documentation

#1895 Removed whitespace from fieldset legend
  src/components/fieldset/_macro.njk
  src/components/label/_macro.njk
Labels: Bug

#1897 Fixed error pattern input focus
  src/components/lists/_macro.njk
  src/components/panel/index.njk
  src/js/inpagelink.js
  src/patterns/help-users-to/correct-errors/examples/errors-proto/errors/index.njk
Labels: Bug

#1901 Design system - fix exclude item from nav
  lib/rendering/helpers/sub-navigation-helper.js
Labels: Bug

#1902 Add aside block to page template
  src/components/question/examples/question-ccs/index.njk
  src/components/question/examples/question-fieldset/index.njk
  src/foundations/layout/page-template/examples/basic/index.njk
  src/foundations/layout/page-template/examples/block-areas/_block-areas.scss
  src/foundations/layout/page-template/examples/block-areas/index.njk
  src/foundations/layout/page-template/examples/custom/index.njk
  src/foundations/layout/page-template/index.njk
  src/layout/_template.njk
  src/patterns/ask-users-for/addresses/examples/address-input-non-editable/register-address/index.njk
  src/patterns/help-users-to/access-support-in-multiple-languages/examples/default/index.njk
  src/patterns/help-users-to/download-resources/examples/download-resources-error/index.njk
  src/patterns/help-users-to/download-resources/examples/download-resources/index.njk
  src/patterns/pages/guide/examples/rtl/index.njk
  src/patterns/pages/news/examples/article/index.njk
  src/patterns/pages/news/examples/category/index.njk
  src/patterns/pages/news/examples/landing/index.njk
  src/patterns/pages/news/examples/tag/index.njk
  src/patterns/pages/question/examples/question-anatomy/index.njk
Labels: Breaking changes

#1970 Updated mutually exclusive validation guidance
  src/components/mutually-exclusive/examples/date-input-error/index.njk
  src/components/mutually-exclusive/index.njk
Labels: Documentation

#1985 Improve phase banner content
  src/components/autosuggest/index.njk
  src/components/feedback/examples/feedback/index.njk
  src/components/phase-banner/examples/phase-banner-alpha/index.njk
  src/components/phase-banner/examples/phase-banner-beta/index.njk
  src/components/phase-banner/index.njk
Labels: Accessibility, Documentation
