Repository ONSdigital/design-system, pull requests merged in 2022-07, with the labels that each got.

#2300 Related content - add flexible content functionality
  config/components.json
  src/components/related-content/_macro.njk
  src/components/related-content/_macro.spec.js
  src/components/related-content/_section-macro.njk
  src/components/related-content/_section-macro.spec.js
  src/components/related-content/examples/related-content-census/index.njk
  src/components/related-content/examples/related-content-general/index.njk
  src/components/related-content/examples/related-content/index.njk
  src/components/related-content/examples/related-links-multiple-rows/index.njk
  src/components/related-content/examples/related-links-single-row/index.njk
  src/components/related-content/examples/related-links-social-media/index.njk
  src/components/related-content/index.njk
  src/patterns/pages/news/examples/landing/index.njk
Labels: Enhancement, Breaking changes

#2277 Add visually hidden screen reader context to onsExternalLink
  src/components/button/_macro-options.md
  src/components/button/_macro.njk
  src/components/button/_macro.spec.js
  src/components/button/examples/button-link-new-window/index.njk
  src/components/external-link/_macro-options.md
  src/components/external-link/_macro.njk
  src/components/external-link/_macro.spec.js
Labels: Accessibility

#2304 Share page - make title optional
  src/components/share-page/_macro-options.md
  src/components/share-page/_macro.njk
Labels: Enhancement

#2261 Removed unnecessary id attributes from svg icons
  src/components/external-link/_macro.njk
  src/components/footer/_macro.njk
  src/components/icons/_macro.njk
Labels: Mark-up change, Accessibility, Breaking changes

#2305 Rationalise footer options and add co-branded option
  src/components/external-link/_macro.njk
  src/components/footer/_footer.scss
  src/components/footer/_macro-options.md
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
  src/components/footer/examples/footer-alt-org/index.njk
  src/components/footer/examples/footer-coat-of-arms/index.njk
  src/components/footer/examples/footer-copyright/index.njk
  src/components/footer/examples/footer-cymraeg/index.njk
  src/components/footer/examples/footer-default/index.njk
  src/components/footer/examples/footer-no-ogl-crest-cymraeg/index.njk
  src/components/footer/examples/footer-no-ogl-crest-nisra/index.njk
  src/components/footer/examples/footer-no-ogl-crest/index.njk
  src/components/footer/examples/footer-no-ogl/index.njk
  src/components/footer/examples/footer-partnership/index.njk
  src/components/footer/examples/footer-powered-by-ons-transactional-cymraeg/index.njk
  src/components/footer/examples/footer-powered-by-ons-transactional/index.njk
  src/components/footer/examples/footer-powered-by-ons/index.njk
  src/components/footer/examples/footer-transactional-no-ogl-crest-copyright/index.njk
  src/components/footer/examples/footer-transactional-no-ogl-crest-cymraeg/index.njk
  src/components/footer/examples/footer-transactional/index.njk
  src/components/footer/examples/footer-warning/index.njk
  src/components/footer/examples/footer/index.njk
  src/components/footer/index.njk
  src/components/icons/_macro.njk
  src/components/icons/_macro.spec.js
Labels: Mark-up change, Breaking changes

#2315 Fixes: header and hero
  src/components/header/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/components/hero/examples/branded/index.njk
  src/foundations/layout/page-template/index.njk
  src/layout/_template.njk
Labels: Bug

#2318 Page config requires variants header property
  src/foundations/layout/page-template/index.njk
  src/layout/_template.njk
Labels: Bug

#2319 Fix typos in _template.njk
  src/layout/_template.njk
Labels: Bug

#2323 Fix: Cookies settings - check for missing cookie type
  src/js/cookies-settings.js
  src/js/cookies-settings.spec.js
Labels: Bug

#2329 Fix font weight on fieldset legends
  src/components/checkboxes/_macro.njk
  src/components/checkboxes/examples/checkboxes-other-radios/index.njk
  src/components/duration/_macro.njk
  src/components/duration/_macro.spec.js
  src/components/fieldset/_fieldset.scss
  src/components/label/_label.scss
  src/components/radios/examples/radios-other-checkboxes/index.njk
  src/components/radios/examples/radios-other-radios/index.njk
Labels: Bug
