Repository ONSdigital/design-system, pull requests merged in 2022-08, with the labels that each got.

#2349 Fix: Make input prefix/suffix params mandatory to render component
  src/components/duration/_macro-options.md
  src/components/input/_macro.njk
  src/components/input/_macro.spec.js
  src/components/input/examples/numbers-combined/index.njk
  src/components/input/examples/prefixed/index.njk
  src/components/input/examples/suffixed/index.njk
  src/components/mutually-exclusive/examples/duration/index.njk
  src/components/mutually-exclusive/examples/number/index.njk
  src/components/mutually-exclusive/mutually-exclusive.duration.spec.js
  src/components/mutually-exclusive/mutually-exclusive.number.spec.js
  src/patterns/ask-users-for/numeric-values/examples/percentage-error/index.njk
  src/patterns/help-users-to/correct-errors/examples/error-details/index.njk
  src/patterns/help-users-to/correct-errors/examples/errors-proto/errors/index.njk
  src/patterns/help-users-to/correct-errors/examples/errors-proto/index.njk
Labels: Bug, Breaking changes

#2013 Collapsible - use details element and update functionality
  src/components/accordion/_macro-options.md
  src/components/accordion/_macro.njk
  src/components/accordion/_macro.spec.js
  src/components/accordion/accordion.dom.js
  src/components/accordion/accordion.js
  src/components/accordion/accordion.spec.js
  src/components/accordion/examples/accordion-simple/index.njk
  src/components/accordion/examples/accordion/index.njk
  src/components/accordion/index.njk
  src/components/collapsible/_collapsible.scss
  src/components/collapsible/_macro-options.md
  src/components/collapsible/_macro.njk
  src/components/collapsible/_macro.spec.js
  src/components/collapsible/collapsible.dom.js
  src/components/collapsible/collapsible.js
  src/components/collapsible/collapsible.spec.js
  src/components/collapsible/examples/collapsible-with-save/index.njk
  src/components/collapsible/examples/collapsible-with-warning/index.njk
  src/components/collapsible/index.njk
  src/js/main.js
Labels: Enhancement, Accessibility, Breaking changes

#2361 Documentation: update jinja2 documentation
  src/pages/guidance/installing-the-design-system/using-nunjucks/index.njk
Labels: Documentation

#2355 Accessible focus styles
  src/components/autosuggest/_autosuggest.scss
  src/components/button/_button.scss
  src/components/checkboxes/_checkbox.scss
  src/components/input/_input-type.scss
  src/components/input/_input.scss
  src/components/radios/_radio.scss
  src/components/relationships/_relationships.scss
  src/components/table/_table.scss
  src/components/tabs/_macro-options.md
  src/components/tabs/_tabs.scss
  src/components/tabs/examples/tabs/index.njk
  src/components/tabs/tabs.js
  src/components/upload/_upload.scss
  src/foundations/style/colours/_template.njk
  src/foundations/style/colours/index.njk
  src/foundations/style/typography/highlighting/_highlight.scss
  src/scss/patternlib.scss
  src/scss/vars/_colors.scss
Labels: Accessibility

#2364 Accessibility: Autosuggest fixes
  src/components/autosuggest/autosuggest.spec.js
  src/components/autosuggest/autosuggest.ui.js
Labels: Bug, Accessibility

#2373 Fix: DS section nav aria-label
  src/views/layouts/_page.njk
Labels: Bug, Accessibility

#2374 Hide native browser search input clear button
  src/components/input/_input.scss
Labels: Bug, Accessibility

#2378 Fix Jinja compatibility issues with v54
  src/components/input/_macro.njk
Labels: Bug

#2366 Accessibility: download resources fixes
  src/components/download-resources/download-resources.js
  src/components/download-resources/download-resources.spec.js
  src/patterns/help-users-to/download-resources/examples/download-resources-error/index.njk
  src/patterns/help-users-to/download-resources/examples/download-resources/index.njk
  src/patterns/help-users-to/download-resources/index.njk
Labels: Bug, Accessibility

#2388 Fix: Hero - remove regex and replace with simple solution
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/components/hero/examples/pre-title-image-dark/index.njk
  src/components/hero/examples/pre-title-image-light/index.njk
Labels: Bug, Breaking changes

#2381 Accessibility - fix DS side navigation tab order
  src/views/layouts/_page.njk
Labels: Bug, Accessibility

#2383 Accessibility: make 'opens in a new tab' consistent
  src/components/button/_macro.njk
  src/components/button/_macro.spec.js
  src/components/external-link/_macro.njk
  src/components/external-link/_macro.spec.js
  src/components/lists/_macro-options.md
  src/components/lists/_macro.njk
  src/components/lists/_macro.spec.js
Labels: Accessibility

#2390 Accessibility: Modal - change title from H1 to H2
  src/components/modal/_macro.njk
Labels: Accessibility

#2377 Accessbility: Sortable table icon colour contrast
  src/components/table/_table.scss
Labels: Bug, Accessibility

#2380 Accessibility: Add DS example page title and heading
  src/views/layouts/_example.njk
Labels: Accessibility

#2391 Accessibility: Added pointer cursor to checkbox input
  src/components/checkboxes/_checkbox.scss
  src/tests/visual/percy.snapshots.js
Labels: Bug, Accessibility

#2398 Fix: Sortable table headers missing when javascript off
  src/components/icons/_macro.njk
  src/components/table/_macro.njk
  src/components/table/_macro.spec.js
  src/components/table/sortable-table.js
Labels: Bug

#2401 Fix: Modal - positioning
  src/components/modal/_modal.scss
Labels: Bug

#2404 Accessibility: Panel - set alert role when success or error type
  src/components/panel/_macro.njk
  src/components/panel/_macro.spec.js
  src/components/panel/examples/success/index.njk
Labels: Accessibility

#2407 Bug: Panel - error panel should only contain aria attributes if a summary (has a title)
  src/components/panel/_macro.njk
Labels: Bug

#2400 Base page template config enhancements
  src/components/browser-banner/_macro-options.md
  src/components/browser-banner/_macro.njk
  src/components/browser-banner/_macro.spec.js
  src/components/footer/_macro-options.md
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/_macro.spec.js
  src/components/navigation/_macro.njk
  src/components/phase-banner/_macro-options.md
  src/components/phase-banner/_macro.njk
  src/components/phase-banner/_macro.spec.js
  src/foundations/layout/page-template/index.njk
  src/layout/_template.njk
Labels: Enhancement

#2412 Fix: Site search button icon/label spacing
  src/components/button/_button.scss
Labels: Bug

#2406 Fix: Header - correct macro options for default logo
  src/components/header/_macro-options.md
Labels: Bug

#2414 Fix: Issues with errors prototype
  src/patterns/help-users-to/correct-errors/examples/error-details/index.njk
  src/patterns/help-users-to/correct-errors/examples/error-summary/index.njk
  src/patterns/help-users-to/correct-errors/examples/errors-proto/errors/index.njk
  src/patterns/help-users-to/correct-errors/examples/errors-proto/index.njk
Labels: Bug, Documentation

#2408 Fix: Use semantically correct element for inputs with prefix/suffix
  src/components/duration/_macro-options.md
  src/components/duration/_macro.njk
  src/components/duration/_macro.spec.js
  src/components/input/_input-type.scss
  src/components/input/_macro-options.md
  src/components/input/_macro.njk
  src/components/input/_macro.spec.js
  src/components/mutually-exclusive/mutually-exclusive.js
  src/patterns/ask-users-for/numeric-values/index.njk
Labels: Bug

#2409 Fix: Checkboxes - open other tab order
  src/components/radios/check-radios.js
Labels: Bug

#2417 Fix: Checkboxes - multiple other fieldsets with selectAllChildren
  src/components/checkboxes/checkbox-with-fieldset.js
  src/components/checkboxes/checkboxes.dom.js
  src/components/checkboxes/examples/checkboxes-other-checkboxes/index.njk
Labels: Bug

#2416 Panel: Add bare type to documentation and test
  src/components/panel/_macro-options.md
  src/components/panel/_macro.njk
  src/components/panel/_macro.spec.js
Labels: Bug
