Repository ONSdigital/design-system, pull requests merged in 2023-10, with the labels that each got.

#2825 Update checklist action config
  .github/workflows/check-checklist.yml
Labels: Documentation

#2821 Update remark-cli
  package.json
  yarn.lock
Labels: Dependencies

#2827 Change widths of components inside card to be their contents width
  src/components/card/_card.scss
  src/components/card/_macro.njk
Labels: Bug

#2826 Remove form config from base page template
  __snapshots__/layout/_template.spec.js.snap
  src/layout/_template.njk
Labels: Breaking changes

#2699 Enhancement/2172/autosuggest allow input params
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  src/components/address-input/_macro.njk
  src/components/address-input/_macro.spec.js
  src/components/autosuggest/_macro-options.md
  src/components/autosuggest/_macro.njk
  src/components/autosuggest/_macro.spec.js
  src/components/autosuggest/autosuggest.spec.js
  src/components/autosuggest/example-autosuggest-country-multiple.njk
  src/components/autosuggest/example-autosuggest-country.njk
  src/components/button/button.dom.js
  src/js/analytics.js
Labels: Breaking changes

#2834 add example pattern for documentation
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-access-denied-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-access-denied-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-access-denied-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-browser-incompatible-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-browser-incompatible-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-browser-incompatible-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-maintenance-notice_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-maintenance-notice_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-maintenance-notice_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-page-not-found-error-with-code_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-page-not-found-error-with-code_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-page-not-found-error-with-code_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-page-not-found-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-page-not-found-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-page-not-found-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-server-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-server-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-server-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-timed-out-error-not-signed-in_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-timed-out-error-not-signed-in_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-timed-out-error-not-signed-in_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-timed-out-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-timed-out-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_error-status-pages_example-timed-out-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_survey-section-introduction-page_example-survey-section-introduction-page_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_survey-section-introduction-page_example-survey-section-introduction-page_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_survey-section-introduction-page_example-survey-section-introduction-page_0_document_2_mobile.png
  src/patterns/error-status-pages/example-access-denied-error.njk
  src/patterns/error-status-pages/example-browser-incompatible-error.njk
  src/patterns/error-status-pages/example-maintenance-notice.njk
  src/patterns/error-status-pages/example-page-not-found-error-with-code.njk
  src/patterns/error-status-pages/example-page-not-found-error.njk
  src/patterns/error-status-pages/example-server-error.njk
  src/patterns/error-status-pages/example-timed-out-error-not-signed-in.njk
  src/patterns/error-status-pages/example-timed-out-error.njk
  src/patterns/survey-section-introduction-page/example-survey-section-introduction-page.njk
Labels: Documentation

#2837 updated siteautosuggest in navigation component
  __snapshots__/layout/_template.spec.js.snap
  src/components/navigation/_macro.njk
  src/components/navigation/_macro.spec.js
  yarn.lock
Labels: Bug
