Repository ONSdigital/design-system, pull requests merged in 2023-02, with the labels that each got.

#2594 Fix: Video - Add an additional class to control iframe ony when iframe is loaded
  src/components/tabs/examples/tabs-details/index.njk
  src/components/video/_video.scss
  src/components/video/video.js
  src/components/video/video.spec.js
Labels: Bug

#2600 Replaced en dashes with double hyphens for BEM modifier classes shown in Type scale example
  src/foundations/style/typography/type-scale/examples/type-scale/index.njk
Labels: Example

#2597 Fix: sortable table - Change from using childNodes[] to querySelector
  src/components/table/_macro.njk
  src/components/table/sortable-table.js
Labels: Bug

#2609 Fix: Table sort button – include icon in click event
  src/components/table/sortable-table.js
Labels: Bug

#2610 Updated buttonContext option description
  src/components/button/_macro-options.md
Labels: Documentation

#2608 Added language options to header docs
  src/components/header/_macro-options.md
Labels: Documentation

#2617 Fix: Prevent Chrome print dialogue creating page break before grid col
  src/scss/print.scss
Labels: Bug
