Repository ONSdigital/design-system, pull requests merged in 2023-08, with the labels that each got.

#2771 Add external link to phase banner
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-alpha_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-beta_0_document_2_mobile.png
  src/components/external-link/example-external-link.njk
  src/components/phase-banner/example-phase-banner-alpha.njk
  src/components/phase-banner/example-phase-banner-beta.njk
Labels: Enhancement

#2772 updated navigation to hide when toggle button is hidden
  src/components/navigation/navigation.js
Labels: Bug

#2764 Update workflow actions to use node 16 versions
  .github/workflows/npm-bundle.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: Enhancement

#2763 Update husky and git hooks
  .husky/post-checkout
  .husky/pre-commit
  package.json
  yarn.lock
Labels: Enhancement

#2774 autosuggest width aligned with input field
  .gitignore
  backstop_data/bitmaps_reference/ds-vr-test__components_address-input_example-address-input_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_addresses_example-address-input-non-editable_0_document_0_desktop.png
  src/components/autosuggest/_autosuggest.scss
  src/components/autosuggest/_macro.njk
Labels: Bug

#2780 first commit
  README.md
  package.json
Labels: Bug

#2779 add accessible tag for phase banner
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-alpha_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-alpha_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-alpha_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-beta_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-beta_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-beta_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-base-page-template-block-areas_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-base-page-template-block-areas_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-base-page-template-block-areas_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_2_mobile.png
  src/components/phase-banner/_macro.njk
Labels: Accessibility

#2778 deactivate backlink in design system
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_panel_example-panel-with-error-summary_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_panel_example-panel-with-error-summary_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_panel_example-panel-with-error-summary_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_panel_example-panel-with-success-message_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_panel_example-panel-with-success-message_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_panel_example-panel-with-success-message_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_relationships_example-relationships-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_relationships_example-relationships-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_relationships_example-relationships-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_icons_example-icons-size_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_icons_example-icons-size_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_icons_example-icons-size_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_addresses_example-address-input-manual-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_addresses_example-address-input-manual-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_addresses_example-address-input-manual-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_confirmation-page_example-confirmation-page_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_confirmation-page_example-confirmation-page_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_confirmation-page_example-confirmation-page_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-error-summary_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-error-summary_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-error-summary_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-success_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-success_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-success_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_save-and-sign-out_example-signed-out_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_save-and-sign-out_example-signed-out_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_save-and-sign-out_example-signed-out_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-success_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-success_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-success_0_document_2_mobile.png
  lib/render-example.js
  src/components/breadcrumbs/_macro.njk
  src/components/breadcrumbs/_macro.spec.js
  src/components/cookies-banner/_macro.njk
  src/components/cookies-banner/_macro.spec.js
  src/components/panel/_macro.spec.js
  src/patterns/cookies-settings/example-cookie-settings-page.njk
Labels: Bug

#2789 Refactor summary hidden span text change
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/example-summary-grouped-total.njk
  src/components/summary/example-summary-grouped-with-errors.njk
  src/components/summary/example-summary-grouped.njk
  src/components/summary/example-summary-household.njk
  src/components/summary/example-summary-hub.njk
  src/components/summary/example-summary-multiple.njk
  src/components/summary/example-summary.njk
Labels: Bug

#2787 add unique links to example
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-lists_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-lists_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-lists_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  src/components/card/example-card-set-with-lists.njk
Labels: Bug

#2728 Update Jest and Puppeteer
  .github/workflows/lighthouse-ci.yml
  .github/workflows/npm-bundle.yml
  .github/workflows/tests.yml
  __snapshots__/layout/_template.spec.js.snap
  package.json
  src/components/download-resources/download-resources.spec.js
  src/components/tabs/tabs.spec.js
  yarn.lock
Labels: Enhancement
