Repository ONSdigital/design-system, pull requests merged in 2023-07, with the labels that each got.

#2700 Feature/2156/add default value to mutually exclusive component or parameter
  src/components/mutually-exclusive/_macro-options.md
  src/components/mutually-exclusive/_macro.njk
  src/components/radios/_macro.njk
Labels: Enhancement

#2705 2158: Add default values to pagination "previous" and "next" paramaters
  src/components/pagination/_macro-options.md
  src/components/pagination/_macro.njk
  src/components/pagination/example-pagination-first.njk
  src/components/pagination/example-pagination-last.njk
  src/components/pagination/example-pagination-with-no-range-indicator.njk
  src/components/pagination/example-pagination.njk
Labels: Enhancement, Sprint 5

#2706 Enhancement/2694/title tag timeline
  src/components/timeline/_macro-options.md
  src/components/timeline/_macro.njk
  src/components/timeline/_macro.spec.js
Labels: Enhancement

#2711 renamed classes inside accordion component to use BEM structure
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-and-reply-to-messages_example-conversation_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-and-reply-to-messages_example-conversation_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-and-reply-to-messages_example-conversation_0_document_2_mobile.png
  src/components/accordion/_macro.njk
  src/components/accordion/_macro.spec.js
  src/components/accordion/accordion.dom.js
  src/components/accordion/accordion.js
Labels: Enhancement

#2717 Feature/1573/add single field error styling to date component
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-error-for-single-field_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-error-for-single-field_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-error-for-single-field_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  src/components/date-input/_macro-options.md
  src/components/date-input/_macro.njk
  src/components/date-input/_macro.spec.js
  src/components/date-input/example-date-input-error-for-single-field.njk
Labels: Enhancement

#2716 Pattern/1644/survey section interstitial page
  backstop_data/bitmaps_reference/ds-vr-test__patterns_survey-interstitial-page_example-survey-interstitial-page_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_survey-interstitial-page_example-survey-interstitial-page_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_survey-interstitial-page_example-survey-interstitial-page_0_document_2_mobile.png
  src/patterns/survey-interstitial-page/example-survey-interstitial-page.njk
Labels: Pattern, Sprint 6

#2713 Update to Node 16 and minor updates to other DS dependencies
  .babelrc
  .github/workflows/lighthouse-ci.yml
  .github/workflows/npm-bundle.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .nvmrc
  src/components/call-to-action/_macro.njk
  yarn.lock
Labels: Dependencies

#2723 Pattern/1643/confirmation page
  backstop_data/bitmaps_reference/ds-vr-test__patterns_confirmation-page_example-confirmation-page_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_confirmation-page_example-confirmation-page_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_confirmation-page_example-confirmation-page_0_document_2_mobile.png
  src/patterns/confirmation-page/example-confirmation-page.njk
Labels: Pattern, Sprint 6

#2741 Enhancement/1826/header footer param naming
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/example-header-external-with-navigation.njk
  src/components/header/example-header-external-with-service-links.njk
  src/components/header/example-header-external-with-sub-navigation.njk
  src/components/header/example-header-internal.njk
  src/components/header/example-header-neutral-for-multicoloured-logo.njk
  src/components/navigation/_macro.njk
Labels: Enhancement

#2743 Enhancement/2734: create visually hidden h2 for section nav component
  src/components/section-navigation/_macro-options.md
  src/components/section-navigation/_macro.njk
  src/components/section-navigation/_macro.spec.js
Labels: Sprint 7

#2756 added wrapping div to align width of input & autosuggest results
  src/components/autosuggest/_autosuggest.scss
  src/components/autosuggest/_macro.njk
Labels: Enhancement

#2757 Bugfix: 2735 Telephone with errors example
  src/patterns/phone-numbers/example-phone-number-error.njk
Labels: Bug
