Repository ONSdigital/design-system, pull requests merged in 2023-12, with the labels that each got.

#2967 Update read-me
  README.md
Labels: Documentation

#2964 Update tags to headings in section navigation component
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  src/components/pagination/_macro-options.md
  src/components/section-navigation/_macro.njk
  src/components/section-navigation/_section-navigation.scss
Labels: Accessibility

#2972 add example for names pattern
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_names_example-name-multiple-input-field_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_names_example-name-multiple-input-field_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_names_example-name-multiple-input-field_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_names_example-name-single-input-field_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_names_example-name-single-input-field_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_names_example-name-single-input-field_0_document_2_mobile.png
  src/patterns/names/example-name-multiple-input-field.njk
  src/patterns/names/example-name-single-input-field.njk
Labels: Example

#2974 Set form using html in template test
  __snapshots__/layout/_template.spec.js.snap
  src/layout/_template.spec.js
Labels: Bug

#2970 Overview Link of SubNavigation
  src/components/header/example-header-external-with-sub-navigation.njk
  src/components/navigation/_macro.njk
Labels: Bug, Community backlog

#2960 Grid sticky functionality fixed in full pages
  backstop_data/bitmaps_reference/ds-vr-test__components_table-of-contents_example-table-of-contents-sticky-full-page_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table-of-contents_example-table-of-contents-sticky-full-page_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table-of-contents_example-table-of-contents-sticky-full-page_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  src/components/table-of-contents/example-table-of-contents-sticky-full-page.njk
  src/components/table-of-contents/toc.spec.js
  src/scss/objects/_page.scss
  src/tests/helpers/rendering.js
Labels: Bug

#2980 Update readme husky command
  README.md
Labels: Documentation

#2977 add search functionality to ds
  .gitignore
  lib/build-search-index.js
  lib/config.indexPage.js
  lib/dev-server.js
  lib/render-page-list.js
  src/layout/_dsTemplate.njk
Labels: Enhancement, Tech improvements
