Repository ONSdigital/design-system, pull requests merged in 2023-09, with the labels that each got.

#2793 added theme option to pageConfig
  .github/workflows/tests.yml
  __snapshots__/layout/_template.spec.js.snap
  src/foundations/page-template/example-base-page-template-block-areas.njk
  src/foundations/page-template/example-basic.njk
  src/layout/_template.njk
Labels: Bug

#2786 Upgrade to node 18 and other dependancies
  .babelrc
  .github/workflows/tests.yml
  .nvmrc
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  ci/common.js
  lighthouse/lighthouse.sh
  package.json
  src/components/navigation/navigation.js
  src/components/tabs/_macro.njk
  src/components/tabs/_macro.spec.js
  src/js/utils/viewport-change.js
  yarn.lock
Labels: Dependencies

#2805 Update various packages minor versions
  .eslintrc.json
  yarn.lock
Labels: Dependencies

#2803 Update prepend-file to v2
  gulpfile.js
  package.json
  src/tests/helpers/debug.js
  src/tests/helpers/puppeteer.js
  yarn.lock
Labels: Dependencies

#2809 Remove qemu fix
  .github/workflows/tests.yml
Labels: Bug

#2801 Fix/2736 error container in pattern marked as hidden but has a focusable element
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  src/components/autosuggest/autosuggest.spec.js
  src/components/autosuggest/autosuggest.ui.js
Labels: Accessibility

#2808 Remove unused dependencies
  package.json
  yarn.lock
Labels: Dependencies

#2798 Update glob to v10
  .gitignore
  lib/create-page-list.js
  lib/generate-static-pages.js
  lighthouse/lighthouse-get-urls.js
  package.json
  src/tests/helpers/url-generator.js
  yarn.lock
Labels: Dependencies

#2816 fix/1302/reduce margin top when page main contains child with panel error
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_relationships_example-relationships-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_relationships_example-relationships-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_relationships_example-relationships-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_2_mobile.png
  src/scss/objects/_page.scss
Labels: Enhancement
