Repository ONSdigital/design-system, pull requests merged in 2023-03, with the labels that each got.

#2611 Fix: Multiple sortable tables with same heading values
  src/components/table/_macro.njk
  src/components/table/_table.scss
  src/components/table/sortable-table.dom.js
  src/components/table/sortable-table.js
Labels: Bug

#2616 Fix: Header sub navigation for full width layout
  src/components/header/_macro.spec.js
  src/components/navigation/_macro.njk
Labels: Bug

#2630 Fix: Add wide and full-width container classes to cookie banner options
  src/components/cookies-banner/_macro-options.md
  src/components/cookies-banner/_macro.njk
  src/components/cookies-banner/_macro.spec.js
Labels: Bug

#2626 Fix printing page breaking inside elements
  src/components/header/_header.scss
  src/scss/base/_typography.scss
  src/scss/print.scss
Labels: Bug

#2624 Add print hidden utility class
  src/scss/print.scss
Labels: Enhancement

#2614 Added missing `variants` parameter to button macro options
  src/components/button/_macro-options.md
Labels: Documentation

#2632 Fix/2631 cookie settings link override
  src/components/cookies-banner/_macro-options.md
  src/components/cookies-banner/_macro.njk
  src/components/cookies-banner/_macro.spec.js
Labels: Bug

#2606 Add snapshot documentation to the readme
  README.md
Labels: Documentation

#2639 Fix: Updated example paths and removed empty folders
  src/components/duration/example-duration-error-for-single-field.njk
  src/components/radios/example-radios.njk
  src/patterns/change-language/example-change-language-english-ireland.njk
  src/patterns/change-language/example-change-language-english.njk
Labels: Bug

#2633 Add extra functionality to onsQuestion
  src/components/question/_macro.njk
  src/components/question/_macro.spec.js
  src/components/question/example-question-ccs.njk
  src/components/question/example-question-fieldset.njk
  src/components/question/example-question-interviewer-note.njk
  src/components/question/example-question-no-fieldset.njk
  src/patterns/question/example-question-anatomy.njk
  yarn.lock
Labels: Enhancement, Needs documentation
