Repository ONSdigital/design-system, pull requests merged in 2023-01, with the labels that each got.

#2559 Add classes parameter to nav element of section-navigation component
  src/components/section-navigation/_macro-options.md
  src/components/section-navigation/_macro.njk
  src/components/section-navigation/_macro.spec.js
Labels: Enhancement

#2564 Fix: focus state on multi lined links
  gulpfile.js
  src/components/card/_card.scss
  src/scss/base/_global.scss
Labels: Bug

#2566 Fix: Pagination - update and simplify logic
  src/components/pagination/_macro.njk
  src/components/pagination/_macro.spec.js
  src/components/pagination/examples/pagination-with-no-range-indicator/index.njk
Labels: Bug, Enhancement

#2552 Change custom base page template example to have 2 languages and not 4
  src/foundations/layout/page-template/examples/custom/index.njk
Labels: Bug

#2573 Fixed invalid html in typescale example
  src/foundations/style/typography/type-scale/examples/type-scale/index.njk
Labels: Bug, Documentation

#2575 Added first and last page examples for long pagination
  src/components/pagination/examples/pagination-first/index.njk
  src/components/pagination/examples/pagination-last/index.njk
Labels: Example

#2580 Fix small masthead logo render
  src/components/header/_macro.njk
Labels: Bug

#2574 Page config footer sign out button property value fix
  src/layout/_template.njk
Labels: Bug

#2576 Remove asideCols from base page template
  src/components/related-content/_macro.njk
  src/components/related-content/_macro.spec.js
  src/foundations/layout/page-template/examples/base-page-template-block-areas/index.njk
  src/foundations/layout/page-template/index.njk
  src/layout/_template.njk
  src/patterns/help-users-to/download-resources/examples/download-resources/index.njk
  src/patterns/pages/guide/examples/rtl/index.njk
  src/patterns/pages/news/examples/article/index.njk
  src/patterns/pages/news/examples/category/index.njk
  src/patterns/pages/news/examples/landing/index.njk
  src/patterns/pages/news/examples/tag/index.njk
Labels: Enhancement, Do not merge, Breaking changes

#2589 Updated phase banner examples content
  src/components/phase-banner/examples/phase-banner-alpha/index.njk
  src/components/phase-banner/examples/phase-banner-beta/index.njk
Labels: Example

#2557 Add snapshot test for base template
  __snapshots__/layout/_template.spec.js.snap
  jest.config.js
  src/components/header/_macro.njk
  src/layout/_template.njk
  src/layout/_template.spec.js
  src/tests/helpers/rendering.js
  src/tests/helpers/snapshotResolver.js
Labels: Enhancement

#2592 Fix - Update base page template snapshot and correct documentation for aside col changes
  __snapshots__/layout/_template.spec.js.snap
  src/foundations/layout/page-template/examples/custom/index.njk
  src/foundations/layout/page-template/index.njk
  src/layout/_template.spec.js
Labels: Bug
