Repository ONSdigital/design-system, pull requests merged in 2023-11, with the labels that each got.

#2879 CTA button component invokes :active with keyboard
  src/components/button/_button.scss
  src/components/button/button.js
Labels: Bug

#2883 Share page component updates to new "𝕏" icon
  backstop_data/bitmaps_reference/ds-vr-test__components_related-content_example-related-content-social-media_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_related-content_example-related-content-social-media_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_related-content_example-related-content-social-media_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_share-page_example-share-page_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_share-page_example-share-page_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_share-page_example-share-page_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-inline-list-with-social-icon-prefix_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-inline-list-with-social-icon-prefix_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-inline-list-with-social-icon-prefix_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-list-with-icon-prefix_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-list-with-icon-prefix_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-list-with-icon-prefix_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-list-with-icon-suffix_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-list-with-icon-suffix_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-list-with-icon-suffix_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-article_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-article_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-article_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-category_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-category_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-category_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-landing_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-landing_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-landing_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_2_mobile.png
  src/components/icon/_macro.njk
  src/components/list/_list.scss
Labels: Bug

#2894 Add form to error prototype to fix submit button
  src/patterns/correct-errors/example-errors-proto.njk
Labels: Bug

#2895 Remove onsCollapsible
  src/components/collapsible/_macro.njk
  src/components/collapsible/_macro.spec.js
  src/components/details/_macro.spec.js
Labels: Breaking changes, Tech improvements

#2943 Fix visual regression test warnings
  .github/workflows/lighthouse-ci.yml
  .github/workflows/macro-and-script-tests.yml
  .github/workflows/npm-bundle.yml
  .github/workflows/release.yml
  .github/workflows/visual-regression-tests.yml
Labels: Bug

#2896 Fix DS hanging on port 3000
  __snapshots__/layout/_template.spec.js.snap
  lib/dev-server.js
  src/layout/_template.njk
Labels: Bug

#2950 update cookies banner to contain a more descriptive message
  src/components/cookies-banner/_macro.njk
  src/components/cookies-banner/_macro.spec.js
Labels: Accessibility

#2944 Revert details component to JS version to fix printing issue
  backstop_data/bitmaps_reference/ds-vr-test__components_accordion_example-accordion-open_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_accordion_example-accordion-open_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  src/components/accordion/_macro.spec.js
  src/components/accordion/accordion.dom.js
  src/components/accordion/accordion.spec.js
  src/components/accordion/example-accordion-open.njk
  src/components/card/_card.scss
  src/components/details/_details.scss
  src/components/details/_macro.njk
  src/components/details/details.dom.js
  src/components/details/details.js
  src/components/details/details.spec.js
  src/components/details/example-details-with-warning.njk
  src/scss/objects/_page.scss
  src/scss/print.scss
  src/tests/helpers/rendering.js
  src/tests/helpers/rendering.spec.js
Labels: Bug

#2947 Selecting an input prefix/suffix should should focus the associated input
  src/components/input/_input-type.scss
  src/components/input/_macro.njk
  src/components/input/_macro.spec.js
  src/components/input/input.dom.js
  src/components/input/input.js
  src/components/input/input.spec.js
  src/js/main.js
  src/tests/helpers/puppeteer.spec.js
Labels: Enhancement

#2954 Overwrite top css to align active menu buttons
  __snapshots__/layout/_template.spec.js.snap
  src/components/header/_header.scss
  src/components/header/_macro.njk
Labels: Bug
