Repository ONSdigital/design-system, pull requests merged in 2023-06, with the labels that each got.

#2666 fix: changed how radio buttons are displayed
  src/components/radios/_radio.scss
Labels: Bug

#2664 bugfix/2185/summary-params-row-title-attr
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  src/components/summary/_macro-options.md
  src/components/summary/example-summary-grouped-total.njk
Labels: Bug

#2668 Fix/243/link text used for multiple different destinations
  src/components/tabs/_macro-options.md
  src/components/tabs/_macro.njk
  src/components/tabs/_macro.spec.js
  src/components/tabs/example-tabs.njk
Labels: Bug, Accessibility

#2640 Wrapped timeout modal example in div with fixed height
  src/components/timeout-modal/example-timeout-modal.njk
Labels: Bug, Example

#2678 Fix/2325/phase banner background color
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-alpha_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-alpha_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-alpha_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-beta_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-beta_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_phase-banner_example-phase-banner-beta_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-base-page-template-block-areas_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-base-page-template-block-areas_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-base-page-template-block-areas_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_2_mobile.png
  src/components/phase-banner/_phase-banner.scss
Labels: Style, Accessibility

#2681 refactor to remove duplicate identifier
  src/components/tabs/_macro.njk
  src/components/tabs/_macro.spec.js
Labels: Bug

#2669 Fix/2104/image component not matching image macro
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-image-for-regular-screens_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-image-for-regular-screens_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-image-for-regular-screens_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-image-for-retina-screens_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-image-for-retina-screens_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-image-for-retina-screens_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-images-for-regular-screens_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-images-for-regular-screens_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-images-for-regular-screens_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-images-for-retina-screens_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-images-for-retina-screens_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_image_example-images-for-retina-screens_0_document_2_mobile.png
  config/components.json
  src/components/image/_image.scss
  src/components/image/_macro-options.md
  src/components/image/_macro.njk
  src/components/image/_macro.spec.js
  src/components/image/example-image-for-regular-screens.njk
  src/components/image/example-image-for-retina-screens.njk
  src/patterns/news/example-article.njk
  src/scss/main.scss
Labels: Bug, Breaking changes

#2680 Bugfix/2222/invalid outputtable component outputs name attribute for trtd entries when trnametdname is provided
  src/components/table/_macro-options.md
  src/components/table/_macro.njk
  src/components/table/example-table-basic.njk
Labels: Bug, Breaking changes

#2683 remove value attribute in select tag
  src/components/select/_macro.njk
Labels: Bug, Breaking changes

#2685 Fix/2143/remove misleading appended value from check char limit component
  src/components/char-check-limit/_macro.njk
  src/components/char-check-limit/_macro.spec.js
  src/components/char-check-limit/character-check.spec.js
  src/components/input/_macro.njk
  src/components/input/_macro.spec.js
  src/components/mutually-exclusive/mutually-exclusive.textarea.spec.js
  src/components/textarea/_macro.njk
  src/components/textarea/_macro.spec.js
  src/components/textarea/textarea.spec.js
Labels: Bug

#2686 2226: nested autoselect button needs additional ghost class
  src/components/checkboxes/_macro.njk
Labels: Bug

#2682 Enhancement/2679/accessible names of change buttons in summary component
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/example-summary-grouped-total.njk
  src/components/summary/example-summary-grouped-with-errors.njk
  src/components/summary/example-summary-grouped.njk
  src/components/summary/example-summary-household.njk
  src/components/summary/example-summary-hub.njk
  src/components/summary/example-summary-multiple.njk
  src/components/summary/example-summary.njk
Labels: Breaking changes

#2687 updated additional attributes parameter on the <select> and <option> elements on the select component
  src/components/select/_macro.njk
Labels: Bug

#2684 Enhancement/2372/improve tab layout
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  src/components/tabs/_macro-options.md
  src/components/tabs/_macro.njk
  src/components/tabs/_macro.spec.js
  src/components/tabs/_tabs.scss
  src/components/tabs/example-tabs.njk
  src/components/tabs/tabs.js
  src/components/tabs/tabs.spec.js
Labels: Enhancement

#2688 Bugfix - 2136 - Cookies Banner Param Rename
  src/components/cookies-banner/_macro-options.md
  src/components/cookies-banner/_macro.njk
  src/components/cookies-banner/_macro.spec.js
Labels: Breaking changes

#2695 Enhancement/2627/video checkappend dnt parameters
  src/components/video/example-video.njk
  src/components/video/video.js
  src/components/video/video.spec.js
Labels: Enhancement

#2698 Feature/2182/add default value to text parameter in skip-to-content component
  __snapshots__/layout/_template.spec.js.snap
  src/components/skip-to-content/_macro-options.md
  src/components/skip-to-content/_macro.njk
  src/components/skip-to-content/_macro.spec.js
Labels: Enhancement
