Repository ONSdigital/design-system, pull requests merged in 2024-07, with the labels that each got.

#3238 Deprecation and Release Policy.
  policies/deprecation-release-policy.md
Labels: Documentation

#3252 Remove duplicate the from release policy
  policies/deprecation-release-policy.md
Labels: Bug

#3255 Remove sanitised test from address mapping
  src/components/address-input/autosuggest.address.js
Labels: Tech improvements

#3261 Fix/3243/fix inconsistency in header example
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-welsh_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-welsh_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-welsh_0_document_2_mobile.png
  src/components/header/example-header-external-welsh.njk
  src/components/radios/_macro.njk
Labels: Bug

#3257 Add Pre-set value in a textarea within a radio
  src/components/radios/_macro.njk
  src/components/radios/_macro.spec.js
Labels: Enhancement

#3260 Remove double error panel on text area component
  src/components/textarea/_macro.njk
  src/components/textarea/_macro.spec.js
Labels: Bug

#3220 Fix focus state on neutral header
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-neutral-for-multicoloured-logo_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-neutral-for-multicoloured-logo_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-neutral-for-multicoloured-logo_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-neutral_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-neutral_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-neutral_0_document_2_mobile.png
  src/components/button/_button.scss
  src/components/header/_header.scss
  src/components/header/_macro.njk
  src/components/header/example-header-external-welsh.njk
  src/components/header/example-header-neutral.njk
  src/components/navigation/_navigation.scss
  src/components/radios/_macro.njk
  src/scss/vars/_colors.scss
Labels: Bug

#3265 Remove ons-grid--column@xs@s from examples that don't use ons-grid--flex
  src/components/back-to-top/example-full-page-back-to-top.njk
  src/components/card/example-card-set-with-images.njk
  src/components/card/example-card-set-with-lists.njk
  src/components/card/example-card-set.njk
  src/patterns/download-resources/example-download-resources.njk
  src/patterns/news/example-article.njk
  src/patterns/news/example-category.njk
  src/patterns/news/example-landing.njk
  src/patterns/news/example-tag.njk
Labels: Bug

#3256 New summary list variant of the list component
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-summary-list_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-summary-list_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_lists_example-summary-list_0_document_2_mobile.png
  src/components/list/_list.scss
  src/components/list/_macro-options.md
  src/foundations/lists/example-summary-list.njk
Labels: Enhancement

#3269 Fix focus states on internal and neutral header
  src/components/header/_header.scss
Labels: Bug

#3271 Fixes bug in section navigation
  backstop_data/bitmaps_reference/ds-vr-test__components_section-navigation_example-section-navigation-single-vertical-with-title_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_section-navigation_example-section-navigation-single-vertical-with-title_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_section-navigation_example-section-navigation-single-vertical-with-title_0_document_2_mobile.png
  src/components/section-navigation/_macro.njk
  src/components/section-navigation/example-section-navigation-single-vertical-with-title.njk
Labels: Bug

#3272 Standardise padding and margin utility classes
  backstop_data/bitmaps_reference/ds-vr-test__components_input_example-input-search-with-character-check_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_input_example-input-search-with-character-check_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_input_example-input-search-with-character-check_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_input_example-input-search_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_input_example-input-search_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_input_example-input-search_0_document_2_mobile.png
  lib/render-example.js
  lib/render-page-list.js
  src/components/header/_macro.spec.js
  src/components/navigation/_macro.njk
  src/components/navigation/_macro.spec.js
  src/components/summary/_macro.njk
  src/layout/_dsTemplate.njk
  src/scss/utilities/_index.scss
  src/scss/utilities/_padding.scss
Labels: Enhancement
