Repository ONSdigital/design-system, pull requests merged in 2024-01, with the labels that each got.

#2986 Update 'id' for the Postcode example to 'postcode'
  src/components/input/example-input-text-width-constrained.njk
Labels: Enhancement, Refined(Tech)

#2989 Added the conditions and class in the input component
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  src/components/input/_input.scss
  src/components/input/_macro.njk
  src/components/label/_macro.njk
Labels: Bug, Refined(Tech)

#2878 update analytics.js file to be compatible with GA4
  src/components/details/_details.scss
  src/components/details/_macro.njk
  src/components/tabs/_macro-options.md
  src/components/tabs/_macro.njk
  src/components/tabs/_macro.spec.js
  src/js/analytics.js
  src/js/main.js
Labels: Bug

#2982 Subnavigation rendered only when needed
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation-removed_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation-removed_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation-removed_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  src/components/header/_macro-options.md
  src/components/header/example-header-external-with-sub-navigation-removed.njk
  src/components/navigation/_macro.njk
  src/components/navigation/navigation.spec.js
Labels: Enhancement

#2999 Update GA var names for char limit
  src/components/char-check-limit/character-limit.js
Labels: Bug

#2997 Update lint-staged and config
  package.json
  yarn.lock
Labels: Bug

#2993 Updates access code text and relevant VR tests
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_access-code_example-access-code_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  src/components/access-code/example-access-code-error.njk
  src/components/access-code/example-access-code.njk
Labels: Bug

#3003 Update npm package build process
  ci/generate-npm-package.js
Labels: Bug

#3001 Add hover states to collapsed menus
  src/components/navigation/_navigation.scss
Labels: Enhancement
