Repository ONSdigital/design-system, pull requests merged in 2024-04, with the labels that each got.

#3119 Fix/411/sign language interpretation not available for video content wcag 22 level aaa
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_video_example-video_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_video_example-video_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_video_example-video_0_document_2_mobile.png
  src/components/tabs/example-tabs-details.njk
  src/components/video/example-video.njk
  src/static/patternlib-img/youtube-example-cover.png
Labels: Accessibility

#3097 Update markdown
  backstop.config.js
  src/components/header/_macro-options.md
  src/components/language-selector/_macro-options.md
Labels: Documentation

#3123 Update external link test
  src/components/external-link/_macro.spec.js
Labels: Enhancement, Tech improvements

#3122 add role of image to icons
  __snapshots__/layout/_template.spec.js.snap
  src/components/icon/_macro.njk
  src/components/icon/_macro.spec.js
Labels: Accessibility

#3132 Embed tab contents not wrapping on video example
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_2_mobile.png
  src/components/tabs/example-tabs-details.njk
  src/scss/utilities/_utilities.scss
Labels: Bug

#3125 Introduced tracking for parent element if child is target of click event.
  src/js/analytics.js
Labels: Bug

#3141 Enhancement/3131/feature ability to pass arbitrary key value pairs in google analytics events
  src/js/analytics.js
Labels: Enhancement

#3144 standardises radio widths
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-descriptions_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-descriptions_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_1_tablet.png
  src/components/radios/_radios.scss
Labels: Enhancement

#3147 Fixed misalignment of circle inside radio input
  src/components/radios/_radio.scss
Labels: Bug

#3148 Add variant for radios with a textarea
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area_0_document_2_mobile.png
  src/components/radios/_macro-options.md
  src/components/radios/_macro.njk
  src/components/radios/example-radios-with-revealed-text-area-expanded.njk
  src/components/radios/example-radios-with-revealed-text-area.njk
Labels: Enhancement

#3149 Updated backstop js config
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-select-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-select-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-select-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-modal_example-timeout-modal_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-modal_example-timeout-modal_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_timeout-panel_example-panel-with-timeout-warning_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_cookies-settings_example-cookie-settings-page_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_cookies-settings_example-cookie-settings-page_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-form_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-a-web-form_example-form_0_document_1_tablet.png
  src/tests/helpers/url-generator.js
Labels: Bug

#3157 Revert to using macOS 12 for VR tests
  .github/workflows/visual-regression-tests.yml
Labels: Dependencies

#3155 Ignore build files from Jest tests
  jest.config.js
Labels: Bug

#3161 Remove `min` and `max` attributes from text type inputs
  src/components/autosuggest/_macro.njk
  src/components/autosuggest/_macro.spec.js
  src/components/date-input/_macro.njk
  src/components/date-input/_macro.spec.js
  src/components/input/_macro-options.md
  src/components/input/example-input-number.njk
  src/components/input/example-input-numeric-values.njk
  src/components/mutually-exclusive/example-mutually-exclusive-number.njk
  src/components/mutually-exclusive/mutually-exclusive.duration.spec.js
  src/components/mutually-exclusive/mutually-exclusive.number.spec.js
Labels: Bug
