Repository ONSdigital/design-system, pull requests merged in 2024-09, with the labels that each got.

#3325 Updated color of check icon for summary list variant in list component
  src/components/list/_macro.njk
Labels: Enhancement

#3267 Add template for migration guides
  migration_guides/70.x.x-to-71.0.0-migration-guide.md
  yarn.lock
Labels: Documentation

#3307 Update parameter from manualLink to manualLinkUrl in Address Input component
  src/components/address-input/_macro-options.md
  src/components/address-input/_macro.njk
  src/components/address-input/_macro.spec.js
  src/components/address-input/autosuggest.address.spec.js
  src/components/address-input/example-address-input-editable.njk
  src/patterns/addresses/example-address-input-non-editable.njk
Labels: Enhancement, Breaking changes

#3306 Update parameter from linkText to videoLinkText in Video Component
  src/components/tabs/example-tabs-details.njk
  src/components/video/_macro-options.md
  src/components/video/_macro.njk
  src/components/video/_macro.spec.js
  src/components/video/example-video.njk
  src/components/video/video.spec.js
Labels: Do not merge, Breaking changes, Tech improvements

#3305 Update param name from title to text in section navigation component
  src/components/section-navigation/_macro-options.md
  src/components/section-navigation/_macro.njk
  src/components/section-navigation/_macro.spec.js
  src/components/section-navigation/example-section-navigation-single-vertical-with-title.njk
  src/components/section-navigation/example-section-navigation-vertical.njk
  src/components/section-navigation/example-section-navigation.njk
Labels: Enhancement, Do not merge, Breaking changes

#3304 Update parameter from linkText to text in external link component
  src/components/external-link/_macro-options.md
  src/components/external-link/_macro.njk
  src/components/external-link/_macro.spec.js
  src/components/external-link/example-external-link.njk
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
  src/components/list/_macro.njk
  src/components/list/_macro.spec.js
  src/components/phase-banner/example-phase-banner-alpha.njk
  src/components/phase-banner/example-phase-banner-beta.njk
  src/components/video/_macro.njk
Labels: Breaking changes, Tech improvements

#3300 Update param name settingsLinkTextURL to settingsLinkURL in Cookies Banner component
  src/components/cookies-banner/_macro-options.md
  src/components/cookies-banner/_macro.njk
  src/components/cookies-banner/_macro.spec.js
Labels: Enhancement, Breaking changes

#3303 Update parameter names in card component
  src/components/card/_macro-options.md
  src/components/card/_macro.njk
  src/components/card/_macro.spec.js
  src/components/card/example-card-set-with-images.njk
  src/components/card/example-card-set-with-lists.njk
  src/components/card/example-card-set.njk
  src/components/card/example-card.njk
Labels: Breaking changes, Tech improvements

#3299 Update parameter names in document list component
  src/components/document-list/_macro-options.md
  src/components/document-list/_macro.njk
  src/components/document-list/_macro.spec.js
  src/components/document-list/example-document-list-article-featured.njk
  src/components/document-list/example-document-list-articles.njk
  src/components/document-list/example-document-list-downloads.njk
  src/components/document-list/example-document-list-search-result-featured.njk
  src/components/document-list/example-document-list-search-results.njk
  src/components/download-resources/download-resources.spec.js
  src/patterns/download-resources/example-download-resources.njk
  src/patterns/news/example-category.njk
  src/patterns/news/example-landing.njk
  src/patterns/news/example-tag.njk
Labels: Breaking changes, Tech improvements

#3295 Update parameter name from url to linkUrl in feedback component
  src/components/feedback/_macro-options.md
  src/components/feedback/_macro.njk
  src/components/feedback/_macro.spec.js
  src/components/feedback/example-feedback-call-to-action.njk
  src/patterns/confirmation-page/example-confirmation-page.njk
Labels: Enhancement, Breaking changes

#3294 Update parameter from link to text in Footer Component
  src/components/footer/_macro-options.md
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
  src/foundations/page-template/example-base-page-template-block-areas.njk
Labels: Breaking changes, Tech improvements

#3293 Update parameter name from url to src in Image Component
  src/components/image/_macro-options.md
  src/components/image/_macro.njk
  src/components/image/_macro.spec.js
  src/components/image/example-image-for-regular-screens.njk
Labels: Breaking changes, Tech improvements

#3292 Update parameter names from LogoImage and LogoURL to image and url a in header component
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/_macro.spec.js
  src/components/header/example-header-multiple-logos.njk
Labels: Enhancement, Breaking changes

#3291 Update parameter subject from text to object type in Message list component
  src/components/message-list/_macro-options.md
  src/components/message-list/_macro.njk
  src/components/message-list/_macro.spec.js
  src/patterns/send-and-reply-to-messages/example-message-list.njk
Labels: Enhancement, Breaking changes

#3290 Update parameter from UnreadLink to UnreadLinkUrl in Message component
  src/components/message/_macro-options.md
  src/components/message/_macro.njk
  src/components/message/_macro.spec.js
  src/patterns/send-and-reply-to-messages/example-conversation.njk
Labels: Breaking changes, Tech improvements

#3275 Removed metadata component
  src/components/metadata/_macro.njk
Labels: Breaking changes, Tech improvements

#3268 Renamed utility class from ons-grid--flex to ons-grid-flex
  __snapshots__/layout/_template.spec.js.snap
  src/components/call-to-action/_macro.njk
  src/components/checkboxes/example-checkboxes-with-hidden-label.njk
  src/components/cookies-banner/_macro.njk
  src/components/footer/_macro.njk
  src/components/header/_macro.njk
  src/components/input/_macro.njk
  src/components/phase-banner/_macro.njk
  src/components/reply/_macro.njk
  src/foundations/page-template/example-base-page-template-block-areas.njk
  src/scss/utilities/_grid.scss
Labels: Bug, Breaking changes

#3329 Fix adding custom list item attributes where items aren't links
  __snapshots__/layout/_template.spec.js.snap
  src/components/list/_macro.njk
Labels: Bug

#3298 Refactor access-code component test file to new format
  src/components/access-code/_macro.spec.js
Labels: Tech improvements

#3323 Refactor Back-to-top component test file to new format
  src/components/back-to-top/_macro.spec.js
Labels: Tech improvements

#3266 Update Puppeteer to v22
  .github/workflows/macro-and-script-tests.yml
  .nvmrc
  README.md
  package.json
  src/components/address-input/autosuggest.address.spec.js
  src/components/autosuggest/autosuggest.spec.js
  src/components/back-to-top/back-to-top.spec.js
  src/components/cookies-banner/cookies-banner.spec.js
  src/components/mutually-exclusive/mutually-exclusive.checkboxes.spec.js
  src/components/mutually-exclusive/mutually-exclusive.date.spec.js
  src/components/mutually-exclusive/mutually-exclusive.duration.spec.js
  src/components/mutually-exclusive/mutually-exclusive.email.spec.js
  src/components/mutually-exclusive/mutually-exclusive.multiple-options.checkboxes.spec.js
  src/components/mutually-exclusive/mutually-exclusive.number.spec.js
  src/components/mutually-exclusive/mutually-exclusive.textarea.spec.js
  src/components/navigation/navigation.spec.js
  src/components/table-of-contents/toc.spec.js
  src/components/table/table.spec.js
  src/components/timeout-modal/timeout-modal.spec.js
  src/components/timeout-panel/timeout-panel.spec.js
  src/components/video/video.spec.js
  src/js/cookies-settings.spec.js
  src/tests/helpers/puppeteer.js
  yarn.lock
Labels: Tech improvements

#3143 Remove call to action component and all references
  src/components/call-to-action/_call-to-action.scss
  src/components/call-to-action/_macro-options.md
  src/components/call-to-action/_macro.njk
  src/components/call-to-action/_macro.spec.js
  src/components/call-to-action/example-call-to-action-default.njk
  src/scss/main.scss
Labels: Do not merge, Breaking changes

#3336 Ensure list item custom attributes are always set on list item
  __snapshots__/layout/_template.spec.js.snap
  migration_guides/70.x.x-to-71.0.0-migration-guide.md
  src/components/list/_macro-options.md
  src/components/list/_macro.njk
  src/components/list/_macro.spec.js
Labels: Breaking changes

#3339 Fix issue with summary link not wrapping
  src/components/summary/_summary.scss
Labels: Bug

#3343 Format and rename test examples file
  lighthouse/lighthouse.sh
  src/components/address-input/autosuggest.address.spec.js
  src/components/header/_macro.spec.js
  src/components/header/_test-examples.js
  src/components/header/_test_examples.js
Labels: Tech improvements

#3334 Update action-gh-release to v2
  .github/workflows/release.yml
Labels: Dependencies

#3330 Refactor browser banner test file to new format
  src/components/browser-banner/_macro.spec.js
Labels: Tech improvements

#3359 Fix list summary variant spacing to match summary component
  backstop_data/bitmaps_reference/ds-vr-test__components_list_example-summary-list_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_list_example-summary-list_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_list_example-summary-list_0_document_2_mobile.png
  src/components/list/_list.scss
  src/components/list/example-summary-list.njk
Labels: Bug

#3354 Add lighthouse files to git ignore
  .gitignore
  README.md
Labels: Tech improvements

#3345 Update husky to v9
  .husky/post-checkout
  .husky/pre-commit
  package.json
  yarn.lock
Labels: Dependencies

#3355 Fixed Lighthouse testing local and in CI
  .github/workflows/lighthouse-ci.yml
  README.md
  lighthouse/lighthouse-get-urls.js
  lighthouse/lighthouse.sh
  lighthouse/lighthouserc.js
  package.json
Labels: Bug

#3361 Update macro tests to allow running of specific tests
  src/components/access-code/_macro.spec.js
  src/components/back-to-top/_macro.spec.js
  src/components/browser-banner/_macro.spec.js
  src/components/header/_macro.spec.js
Labels: Tech improvements

#3368 VR tests moved to ubuntu
  .github/workflows/visual-regression-tests.yml
  backstop.config.js
Labels: Bug

#3365 Format tests
  src/tests/helpers/cheerio.spec.js
  src/tests/helpers/puppeteer.spec.js
  src/tests/helpers/rendering.js
  src/tests/helpers/rendering.spec.js
Labels: Tech improvements

#3370 Fix text-index component example displaying blank page in jinja
  src/components/text-indent/example-text-indent.njk
Labels: Bug

#3372 Remove button variant class when no variant set
  src/components/button/_macro.njk
Labels: Bug

#3320 Refactor Accordion component test file to new format
  src/components/accordion/_macro.spec.js
  src/components/accordion/_test_examples.js
Labels: Tech improvements

#3342 Refactor Breadcrumbs component test file to new format
  src/components/breadcrumbs/_macro.spec.js
  src/components/breadcrumbs/_test_examples.js
Labels: Tech improvements
