Repository ONSdigital/design-system, pull requests merged in 2024-10, with the labels that each got.

#3382 Rename items summary param for compatibility with Jinja
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/example-summary-card-grouped.njk
  src/components/summary/example-summary-grouped-total.njk
  src/components/summary/example-summary-grouped-with-errors.njk
  src/components/summary/example-summary-grouped.njk
  src/components/summary/example-summary-household.njk
  src/components/summary/example-summary-hub-minimal.njk
  src/components/summary/example-summary-hub.njk
  src/components/summary/example-summary-multiple.njk
  src/components/summary/example-summary-no-action.njk
  src/components/summary/example-summary.njk
  src/patterns/hub-and-spoke/example-hub-complete.njk
  src/patterns/hub-and-spoke/example-hub.njk
  src/patterns/hub-and-spoke/example-spoke-summary.njk
Labels: Breaking changes

#3380 Update DS components to ensure compatibility with Jinja
  src/components/details/_macro.njk
  src/components/document-list/_macro.njk
  src/components/panel/_macro.njk
  src/components/share-page/_macro.njk
  src/components/summary/_macro.njk
  src/components/tabs/_macro.njk
  src/components/timeline/_macro.njk
Labels: Bug

#3379 Rename html OGL Link param to current naming standard
  src/components/footer/_macro-options.md
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
  src/components/header/_macro-options.md
Labels: Breaking changes

#3377 Format migration guide
  migration_guides/70.x.x-to-71.0.0-migration-guide.md
Labels: Documentation

#3397 Update migration guide version to 72
  migration_guides/70.x.x-to-72.0.0-migration-guide.md
Labels: Documentation

#3374 Remove unused Codecov dependency
  migration_guides/70.x.x-to-72.0.0-migration-guide.md
  package.json
  src/patterns/survey-interstitial-page/example-survey-interstitial-page.njk
  yarn.lock
Labels: Tech improvements

#3223 Update babel preset env, core and autoprefixer
  package.json
  yarn.lock
Labels: Dependencies

#3398 Fix font size for section navigation header
  backstop_data/bitmaps_reference/ds-vr-test__components_section-navigation_example-section-navigation_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_section-navigation_example-section-navigation_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_section-navigation_example-section-navigation_0_document_2_mobile.png
  src/components/section-navigation/_section-navigation.scss
Labels: Bug

#3405 Fix lighthouse address input test
  src/components/autosuggest/autosuggest.spec.js
  src/components/autosuggest/autosuggest.ui.js
Labels: Accessibility

#3406 Fix lighthouse highlight test
  backstop_data/bitmaps_reference/ds-vr-test__foundations_highlighting_example-highlighting_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_highlighting_example-highlighting_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_highlighting_example-highlighting_0_document_2_mobile.png
  src/foundations/highlighting/example-highlighting.njk
Labels: Accessibility

#3407 Fix lighthouse interstitial page test
  src/patterns/survey-interstitial-page/example-survey-interstitial-page.njk
  src/scss/objects/_page.scss
Labels: Accessibility

#3403 Add textarea variant to checkbox component
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area_0_document_2_mobile.png
  src/components/checkboxes/_checkbox-macro.njk
  src/components/checkboxes/_macro-options.md
  src/components/checkboxes/_macro.njk
  src/components/checkboxes/_macro.spec.js
  src/components/checkboxes/example-checkboxes-with-revealed-text-area-expanded.njk
  src/components/checkboxes/example-checkboxes-with-revealed-text-area.njk
Labels: Enhancement, Community backlog
