Repository ONSdigital/design-system, pull requests merged in 2024-11, with the labels that each got.

#3408 Refactor summary component to fix lighthouse test
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/_summary.scss
Labels: Accessibility

#3410 Fix lighthouse hub and spoke test
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
Labels: Accessibility

#3288 Update Fuse.js configuration to adjust search threshold
  package.json
  src/components/autosuggest/_macro-options.md
  src/components/autosuggest/_macro.njk
  src/components/autosuggest/_macro.spec.js
  src/components/autosuggest/autosuggest.ui.js
  src/components/autosuggest/example-autosuggest-country.njk
  src/components/autosuggest/fuse-config.js
  src/js/analytics.js
  yarn.lock
Labels: Enhancement

#3308 Refactor Address output component test file to new format
  src/components/address-output/_macro.spec.js
  src/components/address-output/_test_examples.js
Labels: Tech improvements

#3414 Fix flakey macro tests
  src/components/address-input/autosuggest.address.spec.js
  src/components/timeout-modal/timeout-modal.spec.js
Labels: Tech improvements, Testing

#3416 Alter section headers to be anchor tags rather than headers
  src/components/section-navigation/_macro.njk
Labels: Bug

#3418 Fix button logic for when `noIcon` param is set to false
  src/components/button/_macro.njk
  src/components/button/_macro.spec.js
Labels: Bug

#3419 Update bowser banner tests to fit new format
  src/components/accordion/_macro.spec.js
  src/components/browser-banner/_macro.spec.js
Labels: Tech improvements, Testing

#3421 Align checkbox indent line with the checkboxes
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-checkboxes-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-checkboxes-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-checkboxes-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-radios-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-radios-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-radios-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-select-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-select-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-select-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-area-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-input-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-input-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-revealed-text-input-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-visible-text-input_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-visible-text-input_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_checkboxes_example-checkboxes-with-visible-text-input_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-clear-button-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-error_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-error_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-checkboxes-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-radios-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-select-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-select-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-select-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-area-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input-expanded_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input-expanded_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-revealed-text-input-expanded_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-visible-text-input_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-visible-text-input_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_radios_example-radios-with-visible-text-input_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_feedback_example-feedback-form-errors_0_document_2_mobile.png
  src/components/checkboxes/_checkbox.scss
Labels: Bug

#3353 Refactor Button component test file to new format
  README.md
  src/components/button/_macro.spec.js
  src/components/button/example-button-group.njk
Labels: Tech improvements

#3316 Refactor Address input component test file to new format
  src/components/address-input/_macro.spec.js
  src/components/address-input/_test-examples.js
Labels: Tech improvements

#3423 Align details component indent line with arrow down icon
  backstop_data/bitmaps_reference/ds-vr-test__components_details_example-details-open_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_details_example-details-open_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_details_example-details-open_0_document_2_mobile.png
  src/components/details/_details.scss
  src/components/details/example-details-open.njk
Labels: Bug

#3425 Refactor External-link component test file to new format
  src/components/external-link/_macro.spec.js
  src/components/external-link/_test_examples.js
Labels: Tech improvements

#3424 Rename table of contents files
  src/components/back-to-top/back-to-top.dom.js
  src/components/back-to-top/back-to-top.js
  src/components/table-of-contents/_macro-options.md
  src/components/table-of-contents/_macro.njk
  src/components/table-of-contents/_macro.spec.js
  src/components/table-of-contents/_table-of-contents.scss
  src/components/table-of-contents/table-of-contents.dom.js
  src/components/table-of-contents/table-of-contents.js
  src/components/table-of-contents/table-of-contents.spec.js
  src/components/table-of-contents/toc.dom.js
  src/components/tabs/_macro-options.md
  src/components/tabs/tabs.js
  src/js/main.js
  src/scss/main.scss
Labels: Tech improvements

#3437 Add padding and margin utility classes without important
  src/scss/utilities/_margin.scss
  src/scss/utilities/_padding.scss
Labels: Enhancement

#3327 Refactor Autosuggest component test file to new format
  src/components/autosuggest/_macro-options.md
  src/components/autosuggest/_macro.spec.js
  src/components/autosuggest/_test-examples.js
Labels: Tech improvements

#3433 Refactor feedback component test file to new format
  src/components/feedback/_macro.spec.js
  src/components/feedback/_test_examples.js
Labels: Tech improvements

#3434 Refactor field component test file to new format
  src/components/field/_macro.spec.js
Labels: Tech improvements

#3432 Remove Line-height in tab component
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs-details_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_tabs_example-tabs_0_document_1_tablet.png
  src/components/tabs/_tabs.scss
Labels: Enhancement
