Repository ONSdigital/design-system, pull requests merged in 2024-02, with the labels that each got.

#3008 Fix/2995/bug misalignment of summary values with long strings during resizing
  src/components/summary/_summary.scss
Labels: Bug

#3011 Update browserlist in package.json
  .gitignore
  package.json
Labels: Documentation, Tech improvements

#3034 updated vr tests to increase the delay to 2 seconds
  src/tests/helpers/url-generator.js
Labels: Enhancement

#3007 update the description list component in the ds it is no longer in alphabetical order
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-description-list_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-description-list_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-description-list_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-description_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-description_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-description_0_document_2_mobile.png
  src/components/description-list/_description-list.scss
  src/components/description-list/_macro-options.md
  src/components/description-list/_macro.njk
  src/components/description-list/_macro.spec.js
  src/components/description-list/example-description-list.njk
  src/components/metadata/_macro-options.md
  src/components/metadata/_macro.njk
  src/patterns/send-and-reply-to-messages/example-conversation.njk
  src/scss/main.scss
Labels: Enhancement

#2994 Enhancement/2890/allow multiple mastheadlogos
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-multiple-logos_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-multiple-logos_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-multiple-logos_0_document_2_mobile.png
  src/components/header/_header.scss
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/_macro.spec.js
  src/components/header/example-header-multiple-logos.njk
  src/scss/utilities/_margin.scss
Labels: Enhancement

#3038 Feature/refactor date input and duration to remove duplicated code
  src/components/date-field-input/_macro.njk
  src/components/date-input/_macro.njk
  src/components/duration/_macro.njk
Labels: Enhancement, Tech improvements

#3040 Improved VR workflow
  .github/workflows/visual-regression-tests.yml
  backstop.config.js
Labels: Enhancement

#3042 Removing unnecessary conditionals: Hero
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/layout/_template.njk
Labels: Enhancement

#3009 Enhancement/2968/add summary card
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-card-grouped_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-card-grouped_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-card-grouped_0_document_2_mobile.png
  src/components/document-list/document-list.scss
  src/components/download-resources/_download-resources.scss
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/_summary.scss
  src/components/summary/example-summary-card-grouped.njk
  src/components/summary/example-summary-hub.njk
  src/patterns/hub-and-spoke/example-hub-complete.njk
  src/patterns/hub-and-spoke/example-hub.njk
  src/scss/vars/_colors.scss
Labels: Enhancement, IxD, Refined(Tech)

#3050 Update setup-node to use Node 20 in actions
  .github/workflows/lighthouse-ci.yml
  .github/workflows/macro-and-script-tests.yml
  .github/workflows/npm-bundle.yml
  .github/workflows/release.yml
Labels: Enhancement

#2990 ⬆️ Back To Top Link ⬆️
  .github/workflows/check-labels.yml
  backstop_data/bitmaps_reference/ds-vr-test__components_back-to-top_example-back-to-top_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_back-to-top_example-back-to-top_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_back-to-top_example-back-to-top_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_back-to-top_example-full-page-back-to-top_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_back-to-top_example-full-page-back-to-top_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_back-to-top_example-full-page-back-to-top_0_document_2_mobile.png
  src/components/back-to-top/_back-to-top.scss
  src/components/back-to-top/_macro-options.md
  src/components/back-to-top/_macro.njk
  src/components/back-to-top/_macro.spec.js
  src/components/back-to-top/back-to-top.dom.js
  src/components/back-to-top/back-to-top.js
  src/components/back-to-top/back-to-top.spec.js
  src/components/back-to-top/example-back-to-top.njk
  src/components/back-to-top/example-full-page-back-to-top.njk
  src/components/checkboxes/_checkbox-macro.njk
  src/components/icon/_macro.njk
  src/js/main.js
  src/scss/main.scss
Labels: Component

#3053 Description list not structured properly for screen readers
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
Labels: Accessibility
