Repository ONSdigital/design-system, pull requests merged in 2024-08, with the labels that each got.

#3168 Header Test Document Refactor
  src/components/header/_macro.spec.js
  src/components/header/_test_examples.js
Labels: Tech improvements

#3279 Update documentation for timeline component
  src/components/timeline/_macro-options.md
Labels: Documentation

#3276 Removed backlink component
  src/components/back-link/example-back-link.njk
Labels: Tech improvements

#3283 Update bug template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: Documentation

#3277 Replace thumbnail image
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-images_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-images_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-images_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-articles_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-articles_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-articles_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-downloads_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-downloads_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-downloads_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_download-resources_example-download-resources_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_download-resources_example-download-resources_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_download-resources_example-download-resources_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-category_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-category_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-category_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-landing_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-landing_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-landing_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_2_mobile.png
  src/components/document-list/_document-list.scss
  src/components/label/_label.scss
  src/scss/vars/_colors.scss
  src/static/img/large/placeholder-card.png
  src/static/img/small/placeholder-card.png
Labels: Accessibility

#3313 Remove spacing around abbreviation text on inputs
  src/components/input/_macro.njk
Labels: Bug

#3315 Document manual process of publishing to NPM
  .github/workflows/npm-bundle.yml
  README.md
Labels: Documentation

#3324 Hero and card bug fixed for jinja environment
  src/components/card/_macro.njk
  src/components/hero/_macro.njk
Labels: Bug

#3318 Updated color of check icon for summary variant in list component to green
  __snapshots__/layout/_template.spec.js.snap
  src/components/list/_list.scss
  src/components/list/_macro.njk
  src/components/list/_macro.spec.js
Labels: Enhancement
