Repository ONSdigital/design-system, pull requests merged in 2024-05, with the labels that each got.

#3179 Refactor document-list macro for compatibility Jinja2 templates
  src/components/document-list/_macro.njk
Labels: Bug

#3177 Refactor share-page macro for compatibility Jinja2 templates
  src/components/share-page/_macro.njk
Labels: Bug

#3187 Update address pattern with correct link
  src/patterns/addresses/example-address-input-non-editable.njk
Labels: Bug

#3183 Updated front matter and links of two examples
  backstop_data/bitmaps_reference/ds-vr-test__patterns_change-language_example-change-language-english_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_change-language_example-change-language-english_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_change-language_example-change-language-english_0_document_2_mobile.png
  src/foundations/page-template/example-base-page-template-block-areas.njk
  src/patterns/change-language/example-change-language-cymraeg.njk
  src/patterns/change-language/example-change-language-english.njk
Labels: Bug

#3197 Allow "Breaking changes" label alongside other labels on PRs
  .github/release.yml
  .github/workflows/check-labels.yml
Labels: CI/CD

#3203 Add "Tech improvements" label to label checker
  .github/release.yml
  .github/workflows/check-labels.yml
Labels: CI/CD

#3186 Update VSCode Extensions links in readme
  README.md
Labels: Documentation

#3175 Update babel preset-env and other dependancies
  .nvmrc
  babel.conf.esm.js
  babel.conf.nomodule.js
  backstop_data/bitmaps_reference/ds-vr-test__components_button_example-button-print_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_cookies-banner_example-cookies-banner-cymraeg_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_cookies-banner_example-cookies-banner-cymraeg_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_cookies-banner_example-cookies-banner-cymraeg_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation-removed_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation-removed_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_extend-session_example-timeout_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub-complete_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-continue_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-start_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-summary_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-and-reply-to-messages_example-conversation_0_document_1_tablet.png
  package.json
  yarn.lock
Labels: Dependencies

#3210 Update incorrect link in address and change language patterns
  src/patterns/addresses/example-address-input-non-editable-confirm-address.njk
  src/patterns/addresses/example-address-input-non-editable-register-address.njk
  src/patterns/change-language/example-change-language-cymraeg.njk
  src/patterns/change-language/example-change-language-english.njk
Labels: Bug

#3198 Update actions to not run check checklist action for Dependabot PRs
  .github/workflows/check-checklist.yml
  src/components/list/_macro.njk
Labels: CI/CD

#3217 Revert "Update babel preset-env and other dependancies"
  .nvmrc
  babel.conf.esm.js
  babel.conf.nomodule.js
  backstop_data/bitmaps_reference/ds-vr-test__components_button_example-button-print_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_cookies-banner_example-cookies-banner-cymraeg_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_cookies-banner_example-cookies-banner-cymraeg_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_cookies-banner_example-cookies-banner-cymraeg_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation-removed_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation-removed_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-external-with-sub-navigation_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__foundations_page-template_example-custom_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_extend-session_example-timeout_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub-complete_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-continue_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-start_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-summary_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_send-and-reply-to-messages_example-conversation_0_document_1_tablet.png
  package.json
  yarn.lock
Labels: Dependencies

#3214 Remove assetsUrl being passed to header and footer
  src/layout/_template.njk
Labels: Tech improvements
