Repository ONSdigital/design-system, pull requests merged in 2024-12, with the labels that each got.

#3443 Documented showMetadataFirst in document-list
  src/components/document-list/_macro-options.md
Labels: Documentation

#3438 New Hero variant - Navy Blue
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-navy-blue_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-navy-blue_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-navy-blue_0_document_2_mobile.png
  src/components/hero/_hero.scss
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/components/hero/example-hero-navy-blue.njk
  src/components/tabs/_tabs.scss
  src/scss/vars/_colors.scss
Labels: Enhancement

#3439 Add inline description list variant
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-inline-description-list_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-inline-description-list_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-inline-description-list_0_document_2_mobile.png
  src/components/description-list/_description-list.scss
  src/components/description-list/_macro-options.md
  src/components/description-list/_macro.njk
  src/components/description-list/_macro.spec.js
  src/components/description-list/example-inline-description-list.njk
Labels: Enhancement

#3460 Added Padding between buttons which are grouped
  backstop_data/bitmaps_reference/ds-vr-test__components_button_example-button-group_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_button_example-button-group_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_button_example-button-group_0_document_2_mobile.png
  src/components/button/_button.scss
Labels: Bug
