Repository ONSdigital/design-system, pull requests merged in 2024-03, with the labels that each got.

#3062 Update placeholder text colour
  backstop_data/bitmaps_reference/ds-vr-test__components_input_example-input-search-with-placeholder_0_document_2_mobile.png
  src/components/card/_macro.njk
  src/components/document-list/document-list.scss
  src/components/document-list/example-document-list-downloads.njk
  src/components/label/_label.scss
  src/components/label/_macro.njk
  src/patterns/guide/example-guide-overview.njk
  src/scss/vars/_colors.scss
Labels: Bug

#3036 Fix/3004/icon in footer not clickable
  __snapshots__/layout/_template.spec.js.snap
  src/components/footer/_footer.scss
  src/components/footer/_macro.njk
  src/components/footer/_macro.spec.js
Labels: Bug

#3066 Fix appearance of checkboxes
  src/components/checkboxes/_checkbox.scss
Labels: Bug

#3067 Exploring Unnecessary Conditionals: Autosuggest
  src/components/autosuggest/_macro-options.md
Labels: Enhancement

#3069 Fix/3035/review ga implementation
  src/js/analytics.js
Labels: Bug

#3068 Update highlight CSS for strong tags
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-search-result-featured_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-search-results_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_document-list_example-document-list-search-results_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-tag_0_document_2_mobile.png
  src/components/access-code/example-access-code-error.njk
  src/components/document-list/example-document-list-search-result-featured.njk
  src/components/document-list/example-document-list-search-results.njk
  src/components/fieldset/_fieldset.scss
  src/components/question/_question.scss
  src/components/question/example-question-interviewer-note.njk
  src/components/relationships/example-relationships-error.njk
  src/foundations/highlighting/example-highlighting.njk
  src/patterns/hub-and-spoke/example-spoke-continue.njk
  src/patterns/news/example-tag.njk
  src/patterns/survey-interstitial-page/example-survey-interstitial-page.njk
  src/patterns/survey-section-introduction-page/example-survey-section-introduction-page.njk
  src/scss/base/_typography.scss
  src/scss/overrides/hcm.scss
Labels: Breaking changes

#3074 alters the padding on autosuggest items to mattch input
  src/components/autosuggest/_autosuggest.scss
Labels: Bug

#3076 Exploring Unnecessary Conditionals: Mutually-Exclusive
  src/components/mutually-exclusive/_macro-options.md
Labels: Enhancement

#3083 Update pagination docs
  src/components/pagination/_macro-options.md
Labels: Documentation

#3087 Updated @babel/preset-env node version
  .babelrc
Labels: Dependencies, Refined(Tech)

#3084 Update duration error message
  backstop_data/bitmaps_reference/ds-vr-test__components_duration_example-duration-error-for-single-field_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_duration_example-duration-error-for-single-field_0_document_2_mobile.png
  src/components/duration/example-duration-error-for-single-field.njk
Labels: Enhancement

#3080 Refactor date and duration components to work in jinja2 environments
  README.md
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-double-field_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-double-field_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-double-field_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-single-field_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-single-field_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_date-input_example-date-input-single-field_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_duration_example-duration-single-field_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_duration_example-duration-single-field_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_duration_example-duration-single-field_0_document_2_mobile.png
  src/components/date-field-input/_macro.njk
  src/components/date-input/_macro.njk
  src/components/date-input/_macro.spec.js
  src/components/date-input/example-date-input-double-field.njk
  src/components/date-input/example-date-input-single-field.njk
  src/components/duration/_macro.njk
  src/components/duration/_macro.spec.js
  src/components/duration/example-duration-single-field.njk
  src/components/metadata/_macro.njk
  src/components/multiple-input-fields/_macro.njk
Labels: Bug

#3095 Add role to SVG logo in the footer
  __snapshots__/layout/_template.spec.js.snap
  src/components/icon/_macro.njk
Labels: Accessibility

#3091 Fix single inputs not clearing for mutually exclusive fields
  src/components/multiple-input-fields/_macro.njk
  src/components/mutually-exclusive/mutually-exclusive.date.spec.js
  src/components/mutually-exclusive/mutually-exclusive.duration.spec.js
Labels: Bug

#3101 Exploring Unnecessary Conditionals: Question
  src/components/question/_macro-options.md
Labels: Enhancement

#3108 Enhancement/3022/explore unnecessary conditionals label
  src/components/label/_macro.njk
Labels: Enhancement

#3099 fixes spacing issue and tests
  backstop_data/bitmaps_reference/ds-vr-test__components_duration_example-duration-error-for-single-field_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_duration_example-duration-error_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_correct-errors_example-errors-proto-errors_0_document_2_mobile.png
  src/components/field/_field-group.scss
Labels: Bug

#3100 Change wording of status
  backstop_data/bitmaps_reference/ds-vr-test__components_status_example-status-success_0_document_2_mobile.png
  src/components/status/example-status-success.njk
Labels: Documentation

#3113 Update GA implementation
  src/js/analytics.js
Labels: Bug
