Repository ONSdigital/design-system, pull requests merged in 2025-05, with the labels that each got.

#3573 Remove lines between each shaded area
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart_0_document_2_mobile.png
  src/components/chart/area-chart.js
Labels: Enhancement

#3435 Refactor Fieldset component test file to new format
  src/components/fieldset/_macro.spec.js
  src/components/fieldset/_test_examples.js
Labels: Tech improvements

#3509 Refactor Card component test file to new format
  lib/functions/extend.js
  src/components/card/_macro.njk
  src/components/card/_macro.spec.js
  src/components/card/_test_examples.js
  src/components/summary/_macro.njk
Labels: Tech improvements

#3567 Fix accessibility console error in Document List
  src/components/document-list/_document-list.scss
  src/components/document-list/_macro.njk
  src/components/document-list/_macro.spec.js
Labels: Bug

#3590 Remove documentIndex variable in document-list
  src/components/document-list/_macro.njk
Labels: Bug

#3586 [Fix] TOC console JS error
  src/components/table-of-contents/table-of-contents.js
Labels: Bug

#3592 [Fix] Decorative SVG icons being announced by screenreaders
  src/components/icon/_macro.njk
Labels: Accessibility

#3593 [Fix] TOC Accessibility updates
  src/components/table-of-contents/_macro-options.md
  src/components/table-of-contents/_macro.njk
  src/components/table-of-contents/_macro.spec.js
Labels: Accessibility

#3595 [Fix] Add headingLevel to Details Panel
  src/components/details-panel/_macro-options.md
  src/components/details-panel/_macro.njk
  src/components/details-panel/_macro.spec.js
  src/components/details-panel/_test-examples.js
Labels: Accessibility

#3596 [Fix] Remove title attributes from SVGs
  src/components/icon/_macro.njk
Labels: Accessibility

#3600 [Fix] Accessibility - Meaningful labels
  src/components/hero/_macro.spec.js
  src/components/icon/_macro.njk
  src/components/language-selector/_macro.njk
Labels: Accessibility

#3571 Check if tickIntervals are set
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_2_mobile.png
  src/components/chart/chart.js
Labels: Bug

#3576 Ensure that the symbol sits in the centre of the line in the legend
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_2_mobile.png
  src/components/chart/common-chart-options.js
Labels: Enhancement

#3577 Fix legend parameter and add better tests
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/_test-examples.js
  src/components/chart/example-clustered-column-chart.njk
  src/components/chart/example-line-chart-with-annotations.njk
  src/components/chart/example-line-chart-with-markers.njk
  src/components/chart/example-scatter-chart.njk
Labels: Bug

#3599 Feature/reference line annotations
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-point-range-and-reference-line-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-point-range-and-reference-line-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-point-range-and-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-range-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-reference-line-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-reference-line-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_2_mobile.png
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/_test-examples.js
  src/components/chart/chart.js
  src/components/chart/common-chart-options.js
  src/components/chart/example-bar-chart-with-point-range-and-reference-line-annotations.njk
  src/components/chart/example-column-chart-with-reference-line-annotations.njk
  src/components/chart/example-line-chart-with-reference-line-annotations.njk
  src/components/chart/range-annotations-options.js
  src/components/chart/reference-line-annotations-options.js
  src/components/chart/utilities.js
Labels: Enhancement

#3601 Extra line series modifications
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_2_mobile.png
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/chart-constants.js
  src/components/chart/chart.js
  src/components/chart/line-chart.js
Labels: Bug

#3605 Update babel dependencies to fix caniuse lite warning
  package.json
  yarn.lock
Labels: Dependencies
