Repository ONSdigital/design-system, pull requests merged in 2025-06, with the labels that each got.

#3612 Don't set a width on the range annotation label when it is set to be 'inside'
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_1_tablet.png
  src/components/chart/range-annotations-options.js
Labels: Bug

#3604 Fix/onsdesys 413/textarea character limit calculated incorrectly
  backstop_data/bitmaps_reference/ds-vr-test__components_textarea_example-textarea-with-character-check_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_textarea_example-textarea-with-character-check_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_textarea_example-textarea-with-character-check_0_document_2_mobile.png
  src/components/char-check-limit/_macro.njk
  src/components/char-check-limit/character-check.js
  src/components/char-check-limit/character-check.spec.js
  src/components/char-check-limit/character-limit.js
  src/components/checkboxes/_macro.spec.js
  src/components/mutually-exclusive/mutually-exclusive.textarea.spec.js
  src/components/textarea/_macro-options.md
  src/components/textarea/_macro.njk
  src/components/textarea/_macro.spec.js
  src/components/textarea/example-textarea-with-character-check.njk
  src/components/textarea/textarea.dom.js
  src/components/textarea/textarea.spec.js
  src/js/main.js
Labels: Bug

#3610 Legend style updates for line charts
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-left-right_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-left-right_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-left-right_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-top-bottom_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-top-bottom_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-top-bottom_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  src/components/chart/common-chart-options.js
  src/components/chart/example-line-chart-with-markers.njk
  src/components/chart/example-scatter-chart.njk
  src/components/chart/line-chart.js
Labels: Enhancement

#3608 Enable tooltips at desktop for all charts, but keep them disabled at mobile
  src/components/chart/common-chart-options.js
  src/components/chart/scatter-chart.js
Labels: Enhancement

#3609 Bar chart data labels overflow fix
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_2_mobile.png
  src/components/chart/bar-chart.js
Labels: Bug

#3619 Fix to reference line annotations to ensure they display for x axis only
  src/components/chart/_macro-options.md
  src/components/chart/utilities.js
Labels: Bug

#3623 Addresses an issue on resizing charts, a bug with the legend and moves some functions to the correct options file
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-custom-reference-line-value_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-range-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-reference-line-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-confidence-levels_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-confidence-levels_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-custom-reference-line-value_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-custom-reference-line-value_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-left-right_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-left-right_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-top-bottom_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-top-bottom_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_1_tablet.png
  src/components/chart/bar-chart.js
  src/components/chart/chart.js
  src/components/chart/common-chart-options.js
  src/components/chart/specific-chart-options.js
Labels: Bug

#3625 Updates to Chart Documentation
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/chart.js
  src/components/chart/columnrange-chart.js
  src/components/chart/example-bar-with-confidence-levels.njk
  src/components/chart/example-column-with-confidence-levels.njk
  src/components/chart/example-scatter-chart.njk
Labels: Documentation

#3618 Add flex grid gap modifier classes
  src/components/card/_card.scss
  src/components/card/example-card-set-with-headline-figures.njk
  src/scss/utilities/_grid.scss
Labels: Enhancement, Style

#3616 Featured article variant of the chart component
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-confidence-levels_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-custom-reference-line-value_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-confidence-levels_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-custom-reference-line-value_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_featured-article_example-featured-article-with-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_featured-article_example-featured-article-with-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_featured-article_example-featured-article-with-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_featured-article_example-featured-article-with-image_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_featured-article_example-featured-article-with-image_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_featured-article_example-featured-article-with-image_0_document_2_mobile.png
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/featured-article/_macro-options.md
  src/components/featured-article/_macro.njk
  src/components/featured-article/_test-examples.js
  src/components/featured-article/example-featured-article-with-chart.njk
  src/components/featured-article/example-featured-article-with-image.njk
  src/components/featured-article/featured-article.scss
  src/components/featured-article/macro.spec.js
  src/scss/main.scss
Labels: Enhancement

#3627 Refactor header macro to fix taborder
  src/components/header/_header.scss
  src/components/header/_macro.njk
  src/scss/utilities/_grid.scss
Labels: Enhancement

#3630 Disable tooltip for confidence interval charts
  src/components/chart/boxplot.js
  src/components/chart/columnrange-chart.js
Labels: Enhancement

#3631 Ensure legend symbols are all 12px by 12px, apart from line charts with markers
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-confidence-levels_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-confidence-levels_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-confidence-levels_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-custom-reference-line-value_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-left-right_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-top-bottom_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  src/components/chart/_chart.scss
  src/components/chart/specific-chart-options.js
Labels: Enhancement

#3620 Basic header styling fixes
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-basic_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-basic_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-basic_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-with-search-button_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-with-search-button_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-with-search-button_0_document_2_mobile.png
  src/components/button/_button.scss
  src/components/header/_header.scss
  src/components/header/_macro.njk
  src/components/header/example-header-basic.njk
  src/components/header/example-header-with-search-button.njk
  src/components/navigation/navigation.js
Labels: Bug

#3642 [Bug] Update z-index for header
  src/components/header/_header.scss
Labels: Bug

#3639 Add axis min/max limit and options to start or end on a tick
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart-with-axis-min-and-max-values_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart-with-axis-min-and-max-values_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-area-chart-with-axis-min-and-max-values_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-axis-min-and-max-values_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-axis-min-and-max-values_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-axis-min-and-max-values_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-axis-min-and-max-values_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-axis-min-and-max-values_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-axis-min-and-max-values_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-axis-min-and-max-values_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-axis-min-and-max-values_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-axis-min-and-max-values_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart-with-axis-min-and-max-values_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart-with-axis-min-and-max-values_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart-with-axis-min-and-max-values_0_document_2_mobile.png
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/example-area-chart-with-axis-min-and-max-values.njk
  src/components/chart/example-bar-chart-with-axis-min-and-max-values.njk
  src/components/chart/example-column-chart-with-axis-min-and-max-values.njk
  src/components/chart/example-line-chart-with-axis-min-and-max-values.njk
  src/components/chart/example-scatter-chart-with-axis-min-and-max-values.njk
  src/components/chart/specific-chart-options.js
Labels: Enhancement

#3647 [DAC] Update details panel with description list markup & add aria label for item URL
  src/components/details-panel/_details-panel.scss
  src/components/details-panel/_macro-options.md
  src/components/details-panel/_macro.njk
  src/components/details-panel/_macro.spec.js
  src/components/details-panel/example-details-panel-open.njk
  src/components/details-panel/example-details-panel.njk
Labels: Enhancement

#3634 Replace hardcoded strings with optional parameter and default fallback text
  __snapshots__/layout/_template.spec.js.snap
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/_macro.spec.js
  src/components/header/_test-examples.js
  src/components/language-selector/_macro-options.md
  src/components/language-selector/_macro.njk
  src/components/language-selector/_macro.spec.js
  src/components/pagination/_macro-options.md
  src/components/pagination/_macro.njk
  src/components/pagination/_macro.spec.js
Labels: Enhancement
