Repository ONSdigital/design-system, pull requests merged in 2025-04, with the labels that each got.

#3528 Headline figures - Card component variant without Sparkline
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-headline-figures_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-headline-figures_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-headline-figures_0_document_2_mobile.png
  src/components/card/_card.scss
  src/components/card/_macro-options.md
  src/components/card/_macro.njk
  src/components/card/_macro.spec.js
  src/components/card/example-card-set-with-headline-figures.njk
  src/foundations/page-template/example-base-page-template-block-areas.njk
  src/scss/utilities/_grid.scss
Labels: Enhancement

#3536 Grey hero variant - fix/update statistics logo (#285)
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_2_mobile.png
  src/components/hero/_hero.scss
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/example-hero-grey.njk
  src/components/icon/_macro.njk
Labels: Bug

#3529 Add information panel to hero
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_2_mobile.png
  src/components/hero/_hero.scss
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/components/hero/example-hero-grey.njk
Labels: Enhancement

#3539 Add in test for new Statistics badge URL in hero component
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_2_mobile.png
  src/components/hero/_hero.scss
  src/components/hero/_macro.spec.js
  src/components/icon/_macro.njk
Labels: Bug

#3534 Enhance TOC component with related links & button
  backstop_data/bitmaps_reference/ds-vr-test__components_table-of-contents_example-table-of-contents-related-links-with-button_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table-of-contents_example-table-of-contents-related-links-with-button_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table-of-contents_example-table-of-contents-related-links-with-button_0_document_2_mobile.png
  src/components/table-of-contents/_macro-options.md
  src/components/table-of-contents/_macro.njk
  src/components/table-of-contents/_macro.spec.js
  src/components/table-of-contents/_table-of-contents.scss
  src/components/table-of-contents/example-table-of-contents-related-links-with-button.njk
Labels: Enhancement

#3533 Set Domain Cookie to Sub-Domains
  src/js/cookies-functions.js
  src/js/cookies-functions.spec.js
Labels: Enhancement

#3535 Feature/chart aspect ratio
  src/components/chart/_chart.scss
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/_test-examples.js
  src/components/chart/annotations-options.js
  src/components/chart/chart.js
  src/components/chart/common-chart-options.js
  src/components/chart/example-clustered-column-chart.njk
  src/components/chart/example-column-chart-with-annotations.njk
  src/components/chart/example-column-chart.njk
  src/components/chart/example-line-chart-with-annotations.njk
  src/components/chart/example-line-chart.njk
  src/components/chart/example-stacked-column-chart.njk
Labels: Enhancement

#3542 Fix pagination alignment
  src/components/pagination/_pagination.scss
Labels: Bug

#3547 Change to-json to to-json.js
  lib/create-nunjucks-environment.js
Labels: Bug

#3546 Update VR snapshots
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_pagination_example-pagination-first_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_pagination_example-pagination-first_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-category_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_news_example-landing_0_document_1_tablet.png
  src/components/chart/example-line-chart-with-annotations.njk
  src/components/pagination/_macro.njk
  src/components/pagination/_pagination.scss
Labels: CI/CD

#3538 Update Breadcrumbs and Topic title styling for navy hero variant
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/hero/_hero.scss
  src/components/hero/_macro.njk
  src/components/hero/example-hero-dark.njk
  src/scss/vars/_colors.scss
Labels: Bug

#3550 Add language-agnostic array `extend()` function
  lib/create-nunjucks-environment.js
  lib/filters/extend.js
  lib/filters/extend.spec.js
  src/components/chart/_macro.njk
Labels: Tech improvements

#3551 Add tick interval params
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_2_mobile.png
  src/components/chart/_chart.scss
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/bar-chart.js
  src/components/chart/chart.js
  src/components/chart/common-chart-options.js
  src/components/chart/example-clustered-column-chart.njk
  src/components/chart/example-column-chart-with-annotations.njk
  src/components/chart/example-column-chart.njk
  src/components/chart/example-column-with-line-chart.njk
  src/components/chart/example-line-chart.njk
Labels: Enhancement

#3521 Fix summary rendering when no valueList is supplied
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-grouped_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-grouped_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-grouped_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-household_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_summary_example-summary-hub-minimal_0_document_1_tablet.png
  src/components/summary/_macro-options.md
  src/components/summary/_macro.njk
  src/components/summary/_macro.spec.js
  src/components/summary/_summary.scss
  src/components/summary/example-summary-grouped.njk
Labels: Bug

#3552 Reinstate line chart example
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_2_mobile.png
  src/components/chart/example-line-chart-with-annotations.njk
Labels: Documentation

#3545 Scatter chart, update markers and small fixes
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-markers_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_2_mobile.png
  src/components/chart/_chart.scss
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/_test-examples.js
  src/components/chart/annotations-options.js
  src/components/chart/bar-chart.js
  src/components/chart/chart-constants.js
  src/components/chart/chart.js
  src/components/chart/common-chart-options.js
  src/components/chart/example-column-with-line-chart.njk
  src/components/chart/example-line-chart-with-markers.njk
  src/components/chart/example-scatter-chart.njk
  src/components/chart/line-chart.js
  src/components/chart/scatter-chart.js
Labels: Enhancement

#3554 Remove Last Point Marker for Bar/Column with Line Charts
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_2_mobile.png
  src/components/chart/chart.js
Labels: Enhancement

#3561 chore: Move extend function to function folder, and update documentation
  lib/create-nunjucks-environment.js
  lib/functions/extend.js
  lib/functions/extend.spec.js
Labels: Tech improvements

#3556 Update column chart spacing to follow Data Viz Guidelines
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-clustered-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-with-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_2_mobile.png
  src/components/chart/chart.js
  src/components/chart/column-chart.js
Labels: Enhancement

#3558 Bug: Update TOC component to use hardcoded button parameters
  src/components/table-of-contents/_macro.njk
  src/components/table-of-contents/example-table-of-contents-related-links-with-button.njk
Labels: Bug

#3560 Bug: Update card title URL parameter to 'optional'
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-headline-figures_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-headline-figures_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_card_example-card-set-with-headline-figures_0_document_2_mobile.png
  src/components/card/_macro-options.md
  src/components/card/_macro.njk
  src/components/card/example-card-set-with-headline-figures.njk
Labels: Bug

#3566 Remove functionality to add bar with line chart
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-with-line-chart_0_document_2_mobile.png
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/_test-examples.js
  src/components/chart/bar-chart.js
  src/components/chart/chart.js
  src/components/chart/example-bar-with-line-chart.njk
Labels: Enhancement
