Repository ONSdigital/design-system, pull requests merged in 2025-01, with the labels that each got.

#3466 Change documentation for legend and legendIsQuestionTitle params
  src/components/mutually-exclusive/_macro-options.md
Labels: Documentation

#3464 Add option to include links in description list
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-inline-description-list_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-inline-description-list_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-inline-description-list_0_document_2_mobile.png
  src/components/description-list/_macro-options.md
  src/components/description-list/_macro.njk
  src/components/description-list/_macro.spec.js
  src/components/description-list/example-inline-description-list.njk
Labels: Enhancement

#3463 Remove panel title for warn, announcement and bare panels
  src/components/panel/_macro-options.md
  src/components/panel/_macro.njk
  src/components/panel/_macro.spec.js
Labels: Bug

#3468 Refactor CharCheckLimit test file to new format
  src/components/char-check-limit/_macro.spec.js
  src/components/char-check-limit/_test-examples.js
Labels: Enhancement

#3472 Restructure list attributes to be set on correct elements
  __snapshots__/layout/_template.spec.js.snap
  src/components/list/_list.scss
  src/components/list/_macro.njk
  src/components/list/_macro.spec.js
Labels: Bug

#3471 Remove ariaResultsLabel form autosuggest
  src/components/address-input/_macro.spec.js
  src/components/address-input/autosuggest.address.spec.js
  src/components/autosuggest/autosuggest.spec.js
  src/components/header/_macro.spec.js
  src/components/header/_test-examples.js
  src/components/header/example-header-external-with-navigation-and-search.njk
  src/components/navigation/_macro.njk
  src/components/navigation/_macro.spec.js
Labels: Tech improvements

#3446 Refactor Document list test file to new format
  src/components/document-list/_macro.spec.js
  src/components/document-list/_test-examples.js
Labels: Enhancement

#3465 Moved description into dl tag in message list component
  src/components/message-list/_macro-options.md
  src/components/message-list/_macro.njk
  src/components/message-list/_macro.spec.js
  src/components/message-list/_message-list.scss
  src/patterns/send-and-reply-to-messages/example-message-list.njk
Labels: Bug

#3470 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: Documentation

#3475 Change html font size to 100% so browser font size settings are respe…
  src/scss/base/_typography.scss
  src/scss/helpers/_mq.scss
Labels: Accessibility

#3482 Increase search button height on small screens
  src/components/button/_button.scss
Labels: Bug
