Repository ONSdigital/design-system, pull requests merged in 2025-02, with the labels that each got.

#3476 Added new Hero variant Pale Blue
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-pale-blue_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-pale-blue_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-pale-blue_0_document_2_mobile.png
  src/components/hero/_hero.scss
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/components/hero/example-hero-pale-blue.njk
  src/scss/vars/_colors.scss
Labels: Enhancement

#3478 Add Menu button in new header variant
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-basic_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-basic_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-basic_0_document_2_mobile.png
  src/components/button/_button.scss
  src/components/header/_header.scss
  src/components/header/_macro-options.md
  src/components/header/_macro.njk
  src/components/header/example-header-basic.njk
Labels: Enhancement

#3492 Fix document list param typo
  src/components/document-list/_macro-options.md
Labels: Documentation

#3493 Update description list inline variant to use grid-auto-flow: column
  backstop_data/bitmaps_reference/ds-vr-test__components_description-list_example-inline-description-list_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_2_mobile.png
  src/components/description-list/_description-list.scss
  src/components/hero/example-hero-grey.njk
Labels: Bug

#3495 Added census 2021 logo in the hero grey variant
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_2_mobile.png
  src/components/hero/_hero.scss
  src/components/hero/_macro-options.md
  src/components/hero/_macro.njk
  src/components/hero/_macro.spec.js
  src/components/hero/example-hero-grey.njk
  src/components/icon/_macro.njk
Labels: Enhancement
