Repository ONSdigital/design-system, pull requests merged in 2025-09, with the labels that each got.

#3720 Fix header button position with navigation
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-button-and-navigation_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-button-and-navigation_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_header_example-header-button-and-navigation_0_document_2_mobile.png
  src/components/header/_macro.njk
  src/components/header/example-header-button-and-navigation.njk
Labels: Bug

#3717 Add Horizontal Scrollable bar to all table variants
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-compact_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-merge-cells_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_table_example-table-sortable_0_document_2_mobile.png
  src/components/table/_macro-options.md
  src/components/table/_macro.njk
  src/components/table/_macro.spec.js
  src/components/table/_table.scss
  src/components/table/example-table-scrollable.njk
Labels: Accessibility

#3709 Introduce aspect ratio param for iframe charts
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-iframe-chart_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-iframe-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-iframe-chart_0_document_2_mobile.png
  src/components/chart/_chart.scss
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/chart-iframe-resize.js
  src/scss/vars/_forms.scss
  src/static/iframe/index.css
  src/static/iframe/index.html
Labels: Bug

#3726 Remove deprecated ariaLabelMsg param from message list
  src/components/message-list/_macro-options.md
  src/components/message-list/_macro.njk
  src/components/message-list/_macro.spec.js
Labels: Breaking changes

#3650 Replace 'toc' in class names with 'table-of-contents'
  src/components/table-of-contents/example-table-of-contents-sticky-full-page.njk
  src/components/table-of-contents/example-table-of-contents-sticky.njk
  src/components/table-of-contents/table-of-contents.dom.js
  src/components/table-of-contents/table-of-contents.spec.js
Labels: Breaking changes

#3730 Create download pattern
  backstop_data/bitmaps_reference/ds-vr-test__patterns_download_example-download_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_download_example-download_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_download_example-download_0_document_2_mobile.png
  src/patterns/download-resources/example-download-resources.njk
  src/patterns/download/example-download.njk
Labels: Pattern

#3736 Fix hub and spoke example links
  backstop_data/bitmaps_reference/ds-vr-test__patterns_extend-session_example-timeout_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_extend-session_example-timeout_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_extend-session_example-timeout_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub-complete_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub-complete_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub-complete_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-hub_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-continue_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-continue_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-continue_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-start_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-start_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-start_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-summary_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-summary_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__patterns_hub-and-spoke_example-spoke-summary_0_document_2_mobile.png
  src/components/button/example-button-new-window.njk
  src/patterns/extend-session/example-timeout.njk
  src/patterns/hub-and-spoke/example-hub-complete.njk
  src/patterns/hub-and-spoke/example-hub.njk
  src/patterns/hub-and-spoke/example-spoke-continue.njk
  src/patterns/hub-and-spoke/example-spoke-start.njk
  src/patterns/hub-and-spoke/example-spoke-summary.njk
Labels: Documentation

#3738 Revert version change
  package.json
Labels: Dependencies
