Repository ONSdigital/design-system, pull requests merged in 2025-08, with the labels that each got.

#3663 High contrast mode for charts
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-point-range-and-reference-line-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-point-range-and-reference-line-annotations_0_document_1_tablet.png
  src/components/chart/_chart.scss
  src/components/chart/example-bar-chart-with-point-range-and-reference-line-annotations.njk
  src/components/chart/range-annotations-options.js
Labels: Accessibility

#3676 Improve focus states for chart
  src/components/chart/_chart.scss
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/_test-examples.js
  src/components/chart/common-chart-options.js
Labels: Accessibility

#3700 Added option to use external breadcrumbs in hero component
  __snapshots__/layout/_template.spec.js.snap
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-dark-with-external-breadcrumbs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-dark-with-external-breadcrumbs_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-dark-with-external-breadcrumbs_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-default-with-external-breadcrumbs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-default-with-external-breadcrumbs_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-default-with-external-breadcrumbs_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey-with-external-breadcrumbs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey-with-external-breadcrumbs_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey-with-external-breadcrumbs_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-navy-blue-with-external-breadcrumbs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-navy-blue-with-external-breadcrumbs_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-navy-blue-with-external-breadcrumbs_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-navy-blue_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-pale-blue-with-external-breadcrumbs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-pale-blue-with-external-breadcrumbs_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-pale-blue-with-external-breadcrumbs_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-pale-blue_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-with-external-breadcrumbs_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-with-external-breadcrumbs_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-with-external-breadcrumbs_0_document_2_mobile.png
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/_macro-options.md
  src/components/breadcrumbs/_macro.njk
  src/components/breadcrumbs/_macro.spec.js
  src/components/hero/_hero.scss
  src/components/hero/_macro.njk
  src/components/hero/example-hero-dark-with-external-breadcrumbs.njk
  src/components/hero/example-hero-default-with-external-breadcrumbs.njk
  src/components/hero/example-hero-grey-with-external-breadcrumbs.njk
  src/components/hero/example-hero-navy-blue-with-external-breadcrumbs.njk
  src/components/hero/example-hero-pale-blue-with-external-breadcrumbs.njk
Labels: Enhancement

#3714 Update docs around installing Yarn
  README.md
Labels: Documentation
