Repository ONSdigital/design-system, pull requests merged in 2025-07, with the labels that each got.

#3648 Add footnotes below the chart
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart-with-point-range-and-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-bar-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-range-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-inside_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-left-right_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-range-annotations-outside-top-bottom_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-reference-line-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-scatter-chart_0_document_2_mobile.png
  src/components/chart/_chart.scss
  src/components/chart/_macro-options.md
  src/components/chart/_macro.njk
  src/components/chart/_macro.spec.js
  src/components/chart/annotations-options.js
  src/components/chart/example-bar-chart.njk
  src/components/chart/example-line-chart.njk
  src/components/chart/example-scatter-chart.njk
  src/components/chart/range-annotations-options.js
  src/components/chart/reference-line-annotations-options.js
Labels: Enhancement

#3653 Enable Overflow for Last Label on Horizontal Axis for Charts
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-column-chart-with-axis-min-and-max-values_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_0_desktop.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_1_tablet.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-line-chart-with-annotations_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_chart_example-stacked-column-chart_0_document_2_mobile.png
  backstop_data/bitmaps_reference/ds-vr-test__components_featured-article_example-featured-article-with-chart_0_document_2_mobile.png
  src/components/chart/_chart.scss
  src/components/chart/_macro.njk
  src/components/chart/bar-chart.js
  src/components/chart/chart.js
  src/components/chart/example-line-chart-with-annotations.njk
Labels: Enhancement

#3657 Added new Header params in pageConfig
  __snapshots__/layout/_template.spec.js.snap
  src/layout/_template.njk
  src/layout/_template.spec.js
Labels: Enhancement

#3672 ONSDESYS-555 - Fix h2 style within card component
  src/scss/objects/_page.scss
Labels: Bug

#3668 Code scanning alert 8: Add permissions to release action
  .github/workflows/release.yml
Labels: CI/CD

#3666 Code scanning alert 6: Add permissions to lighthouse action
  .github/workflows/lighthouse-ci.yml
Labels: CI/CD

#3677 Code scanning alert 34: Incomplete string escaping or encoding
  src/components/tabs/tabs.js
Labels: Tech improvements

#3688 Code scanning alert 27: DOM text reinterpreted as HTML in video.js
  src/components/video/video.js
Labels: CI/CD

#3691 Code scanning alert 13: DOM text reinterpreted as HTML in accordion.js
  src/components/accordion/accordion.js
Labels: CI/CD

#3690 Code scanning alert 24: DOM text reinterpreted as HTML in mutually-exclusive.js
  src/components/mutually-exclusive/mutually-exclusive.js
Labels: CI/CD

#3689 Code scanning alerts 25 26 - DOM text reinterpreted as HTML in clear-radios.js
  src/components/radios/clear-radios.js
Labels: CI/CD

#3686 Code scanning alert 33: DOM text reinterpreted as HTML in timeout.js
  src/js/timeout.js
Labels: CI/CD

#3685 Code scanning alerts 44 45: DOM text reinterpreted as HTML in relationships.js
  src/components/relationships/relationships.js
Labels: CI/CD
